//! [`PatternFlowState`] — the pattern-loop, pattern-break and position-jump state machine,
//! parameterised by a [`PatternFlow`] the module's dialect chose.
//!
//! # Why this is shared and the effects are not
//!
//! Design goal 7 keeps each format's effect *semantics* in its own crate, and that stays
//! true: MOD spells this `E60` / `E6x` / `Bxx` / `Dxx` and S3M spells it `SB0` / `SBx` /
//! `Bxx` / `Cxx`, and each processor decodes its own bytes. What is genuinely shared is
//! the *bookkeeping* — one target, one counter, and the four ways a loop jump can
//! interact with a break already seen or still to come on the same row. Duplicating that
//! in two crates is how the two would drift.
//!
//! # The reference
//!
//! This is libxmp's `src/flow.c` at the pinned corpus revision, function for function:
//! [`PatternFlowState::pattern_loop`] is `libxmp_process_pattern_loop`,
//! [`PatternFlowState::pattern_jump`] is `libxmp_process_pattern_jump`, and
//! [`PatternFlowState::pattern_break`] is `libxmp_process_pattern_break`. The `-1`
//! sentinels of `f->loop_start`, `f->loop_dest`, `f->jump` and `f->loop_param` are spelled
//! [`Option`] here; nothing else is changed, because the conformance dumps this is
//! measured against were generated by exactly that code.
//!
//! [`PatternFlowState::jump`] is libxmp's `next_row`: a pending break or position jump
//! wins over a loop destination chosen on the same row, which is also what ProTracker 2.3D
//! does — its `mt_LoopFn` clears `mt_PBreakPos` and `mt_NextPosition` then advances the
//! order anyway.

use alloc::boxed::Box;
use alloc::vec;
use starplayer_core::quirks::PatternFlow;

use crate::sequencer::Jump;

/// One channel's loop target and counter — libxmp's `f->loop[chn]`.
///
/// Both start at zero, exactly as `libxmp_reset_flow` initialises them; only the *global*
/// target has an "unset" state, and that is [`PatternFlowState::global_start`].
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Hash)]
struct ChannelLoop {
    start: u16,
    count: u8,
}

/// The song's pattern-loop and break/jump bookkeeping for one loaded module.
///
/// Allocated once, when the processor is built. Every method is allocation-free and
/// panic-free, because they all run inside `render()`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PatternFlowState {
    flow: PatternFlow,
    channels: Box<[ChannelLoop]>,
    /// libxmp `f->loop_start`; `None` is its `-1`.
    global_start: Option<u16>,
    /// libxmp `f->loop_count`.
    global_count: u8,
    /// libxmp `f->loop_dest`; `None` is its `-1`. Row-scoped.
    loop_destination: Option<u16>,
    /// libxmp `f->loop_param >= 0`. Row-scoped, and only read under
    /// [`PatternFlow::first_effect_only`].
    loop_effect_seen: bool,
    /// libxmp `f->pbreak`. Row-scoped.
    pending_break: bool,
    /// libxmp `f->jump`; `None` is its `-1`. Row-scoped.
    jump_order: Option<u16>,
    /// libxmp `f->jumpline`. Row-scoped.
    jump_row: u16,
}

impl PatternFlowState {
    /// A fresh state machine for `channel_count` channels under `flow`.
    pub fn new(flow: PatternFlow, channel_count: usize) -> PatternFlowState {
        PatternFlowState {
            flow,
            channels: vec![ChannelLoop::default(); channel_count].into_boxed_slice(),
            global_start: None,
            global_count: 0,
            loop_destination: None,
            loop_effect_seen: false,
            pending_break: false,
            jump_order: None,
            jump_row: 0,
        }
    }

    /// The flow rules in force. Fixed for the lifetime of the loaded module.
    pub const fn flow(&self) -> PatternFlow { self.flow }

    /// Start a new row: clear everything libxmp's `next_row` clears.
    ///
    /// Also called at the top of each pattern-delay repeat, because a repeat re-runs the
    /// row's tick-zero effects and must not inherit the previous pass's decisions.
    pub fn begin_row(&mut self) {
        self.loop_destination = None;
        self.loop_effect_seen = false;
        self.pending_break = false;
        self.jump_order = None;
        self.jump_row = 0;
    }

    /// The song moved to another order or pattern — libxmp's `next_order`.
    ///
    /// A no-op unless the dialect sets [`PatternFlow::pattern_reset`], which Scream
    /// Tracker 3 and Imago Orpheus do and ProTracker, Octalyser, Digital Tracker and
    /// ModPlug 1.16 do not.
    pub fn position_changed(&mut self) {
        if !self.flow.pattern_reset { return; }
        self.global_start = None;
        self.global_count = 0;
        for channel in self.channels.iter_mut() { *channel = ChannelLoop::default(); }
    }

    /// Everything a seek must drop: libxmp's `libxmp_reset_flow`.
    pub fn reset(&mut self) {
        self.global_start = None;
        self.global_count = 0;
        for channel in self.channels.iter_mut() { *channel = ChannelLoop::default(); }
        self.begin_row();
    }

    /// `E6x` / `SBx` — libxmp's `libxmp_process_pattern_loop`.
    ///
    /// `channel` is the channel the effect sits on, `row` the row it sits on, and
    /// `parameter` its low nibble: zero marks the loop target, non-zero performs a loop.
    pub fn pattern_loop(&mut self, channel: usize, row: u16, parameter: u8) {
        // Digital Tracker: only the first E60 or E6x on a row is handled at all.
        if self.flow.first_effect_only && self.loop_effect_seen { return; }
        self.loop_effect_seen = true;

        let mut looped = false;
        if parameter == 0 {
            // Octalyser, Liquid Tracker: E60 is ignored while this counter is running.
            if self.flow.ignore_target_while_looping && self.count(channel) >= 1 { return; }
            self.set_start(channel, row);
        } else {
            if self.start_is_unset() {
                // Scream Tracker 3.01: an SBx with no SB0 before it targets its own row.
                self.set_start(channel, if self.flow.init_same_row { row } else { 0 });
            }
            match self.count(channel) {
                0 => {
                    // ModPlug 1.16: only begin a loop if no other channel is looping.
                    if self.flow.one_at_a_time
                        && self.channels.iter().enumerate().any(|(other, state)| other != channel && state.count != 0)
                    {
                        return;
                    }
                    self.set_count(channel, parameter);
                    self.loop_destination = Some(self.start(channel));
                    looped = true;
                }
                remaining => {
                    self.set_count(channel, remaining - 1);
                    if remaining - 1 != 0 {
                        self.loop_destination = Some(self.start(channel));
                        looped = true;
                    } else {
                        // Scream Tracker 3, Impulse Tracker 2.10+: the loop target
                        // advances past the SBx row when the loop ends.
                        if self.flow.end_advances { self.set_start(channel, row.saturating_add(1)); }
                        // Octalyser, Liquid Tracker: a finished loop cancels this row's
                        // loop destination.
                        if self.flow.end_cancels { self.loop_destination = None; }
                    }
                }
            }
        }

        if !looped || !self.pending_break { return; }
        // Imago Orpheus, Liquid Tracker: the loop destination replaces the break's row.
        if self.flow.shared_break { self.jump_row = self.loop_destination.unwrap_or(0); }
        // Scream Tracker 3, Impulse Tracker: a loop jump cancels a break already seen.
        if self.flow.unset_break && self.jump_order.is_none() { self.pending_break = false; }
        if self.flow.unset_jump && self.jump_order.is_some() {
            self.pending_break = false;
            self.jump_order = None;
        }
    }

    /// `Bxx` — libxmp's `libxmp_process_pattern_jump`. Returns whether the jump was taken
    /// rather than blocked, so a processor can keep its own row bookkeeping in step.
    pub fn pattern_jump(&mut self, order: u16) -> bool {
        if self.flow.delay_jump && self.loop_destination.is_some() { return false; }
        self.pending_break = true;
        self.jump_order = Some(order);
        // ProTracker: a Bxx resets the row a Dxx on an earlier channel chose. Scream
        // Tracker 3, Impulse Tracker and ModPlug keep it.
        if !self.flow.jump_keeps_break_row { self.jump_row = 0; }
        true
    }

    /// `Cxx` / `Dxx` — libxmp's `libxmp_process_pattern_break`. Returns whether the break
    /// was taken rather than blocked.
    pub fn pattern_break(&mut self, row: u16) -> bool {
        if self.flow.delay_break && self.loop_destination.is_some() { return false; }
        self.pending_break = true;
        self.jump_row = row;
        true
    }

    /// Where the song goes when this row's tick budget is spent, or `None` to carry on.
    ///
    /// libxmp's `next_row`: a pending break or position jump discards the loop
    /// destination, and a loop destination is otherwise a jump inside the pattern.
    pub fn jump(&self) -> Option<Jump> {
        if self.pending_break {
            return Some(match self.jump_order {
                Some(order) => Jump::to_order_row(order, self.jump_row),
                None => Jump::break_to_row(self.jump_row),
            });
        }
        self.loop_destination.map(Jump::within_pattern_to_row)
    }

    /// Whether a loop jump has already been chosen on this row. The processors use it to
    /// keep their own "this row broke" bookkeeping honest.
    pub const fn looped_this_row(&self) -> bool { self.loop_destination.is_some() }

    /// Whether a break or position jump is pending for the end of this row.
    pub const fn breaking_this_row(&self) -> bool { self.pending_break }

    /// The loop target in force for `channel` — the global one under
    /// [`PatternFlow::global_target`], this channel's otherwise.
    pub fn start(&self, channel: usize) -> u16 {
        match self.flow.global_target {
            true => self.global_start.unwrap_or(0),
            false => self.channels.get(channel).map_or(0, |state| state.start),
        }
    }

    /// The loop counter in force for `channel`.
    ///
    /// libxmp's `FLOW_LOOP_ONE_AT_A_TIME` test reads the per-channel counters directly, and
    /// no dialect combines it with a global counter, so the two never have to agree.
    pub fn count(&self, channel: usize) -> u8 {
        match self.flow.global_count {
            true => self.global_count,
            false => self.channels.get(channel).map_or(0, |state| state.count),
        }
    }

    /// Whether the target is still at libxmp's `-1`. Only the global target has that
    /// state; per-channel targets start at row zero and are never "unset".
    fn start_is_unset(&self) -> bool { self.flow.global_target && self.global_start.is_none() }

    fn set_start(&mut self, channel: usize, row: u16) {
        match self.flow.global_target {
            true => self.global_start = Some(row),
            false => if let Some(state) = self.channels.get_mut(channel) { state.start = row; },
        }
    }

    fn set_count(&mut self, channel: usize, count: u8) {
        match self.flow.global_count {
            true => self.global_count = count,
            false => if let Some(state) = self.channels.get_mut(channel) { state.count = count; },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use starplayer_core::quirks::{ModLoopDialect, S3mLoopDialect};

    fn state(flow: PatternFlow) -> PatternFlowState { PatternFlowState::new(flow, 4) }

    #[test]
    fn protracker_counts_down_per_channel_and_keeps_its_mark_across_patterns() {
        let mut flow = state(ModLoopDialect::ProTracker.flow());
        flow.begin_row();
        flow.pattern_loop(0, 4, 0);
        assert_eq!(flow.jump(), None, "E60 only marks the target");
        for expected in [3u8, 2, 1, 0] {
            flow.begin_row();
            flow.pattern_loop(0, 8, 3);
            assert_eq!(flow.count(0), expected);
            assert_eq!(flow.jump().is_some(), expected != 0, "count {expected}");
        }
        flow.position_changed();
        assert_eq!(flow.start(0), 4, "ProTracker's n_pattpos survives a pattern change");
    }

    #[test]
    fn scream_tracker_321_shares_one_counter_and_advances_the_target_when_the_loop_ends() {
        let mut flow = state(S3mLoopDialect::ScreamTracker321.flow());
        flow.begin_row();
        flow.pattern_loop(0, 4, 0);
        flow.begin_row();
        flow.pattern_loop(0, 8, 4);
        assert_eq!(flow.count(0), 4, "the first SBx stores its own parameter");
        for (channel, expected) in [(1usize, 3u8), (2, 2), (3, 1)] {
            flow.pattern_loop(channel, 8, 2);
            assert_eq!(flow.count(0), expected, "every further SBx on the row spends one iteration of the one global counter");
        }
        flow.pattern_loop(0, 8, 2);
        assert_eq!(flow.start(0), 9, "the target advances past the SBx row when the loop ends");
    }

    #[test]
    fn scream_tracker_321_blocks_a_break_before_and_after_the_loop_jump() {
        let mut flow = state(S3mLoopDialect::ScreamTracker321.flow());
        flow.begin_row();
        flow.pattern_loop(0, 4, 0);

        flow.begin_row();
        assert!(flow.pattern_break(12), "a break with no loop yet is taken");
        flow.pattern_loop(1, 8, 2);
        assert_eq!(flow.jump(), Some(Jump::within_pattern_to_row(4)), "the loop jump cancels the break already seen");
        assert!(!flow.pattern_jump(3), "and blocks a Bxx that follows it on the row");
        assert_eq!(flow.jump(), Some(Jump::within_pattern_to_row(4)));
    }

    #[test]
    fn scream_tracker_301_targets_its_own_row_and_lets_a_break_through() {
        let mut flow = state(S3mLoopDialect::ScreamTracker301.flow());
        flow.begin_row();
        flow.pattern_loop(0, 8, 5);
        assert_eq!(flow.start(0), 8, "with no SB0 before it, ST3.01 loops back to the SBx row itself");
        assert_eq!(flow.jump(), Some(Jump::within_pattern_to_row(8)));
        assert!(flow.pattern_jump(1), "ST3.01 does not block a Bxx on a loop row");
        assert_eq!(flow.jump(), Some(Jump::to_order_row(1, 0)));
    }

    #[test]
    fn modplug_starts_a_loop_only_while_no_other_channel_is_looping() {
        let mut flow = state(S3mLoopDialect::ModPlug116.flow());
        flow.begin_row();
        flow.pattern_loop(0, 0, 0);
        flow.pattern_loop(1, 0, 0);

        flow.begin_row();
        flow.pattern_loop(0, 4, 2);
        assert_eq!(flow.count(0), 2);
        flow.pattern_loop(1, 4, 2);
        assert_eq!(flow.count(1), 0, "channel 1 may not begin while channel 0's counter runs");
    }

    #[test]
    fn imago_orpheus_rewrites_a_break_row_rather_than_cancelling_a_jump() {
        let mut flow = state(S3mLoopDialect::ImagoOrpheus.flow());
        flow.begin_row();
        flow.pattern_loop(0, 2, 0);

        flow.begin_row();
        assert!(flow.pattern_break(12));
        flow.pattern_loop(0, 6, 3);
        assert_eq!(flow.jump(), Some(Jump::within_pattern_to_row(2)), "the loop cancels a bare break");

        flow.begin_row();
        assert!(flow.pattern_jump(5));
        flow.pattern_loop(0, 6, 3);
        assert_eq!(flow.jump(), Some(Jump::to_order_row(5, 2)), "a Bxx survives, but takes the loop destination as its row");
    }

    #[test]
    fn octalyser_ignores_a_target_mark_while_its_global_counter_runs() {
        let mut flow = state(ModLoopDialect::Octalyser.flow());
        flow.begin_row();
        flow.pattern_loop(0, 2, 0);
        flow.begin_row();
        flow.pattern_loop(0, 6, 3);
        assert_eq!(flow.count(0), 3);
        flow.begin_row();
        flow.pattern_loop(1, 9, 0);
        assert_eq!(flow.start(0), 2, "E60 is ignored while a loop is running");
    }

    #[test]
    fn digital_tracker_runs_only_the_first_loop_effect_on_a_row() {
        let mut flow = state(ModLoopDialect::DigitalTracker.flow());
        flow.begin_row();
        flow.pattern_loop(0, 3, 0);
        flow.pattern_loop(1, 3, 2);
        assert_eq!(flow.start(0), 3);
        assert_eq!(flow.count(0), 0, "the second E6x on the row is not executed at all");
    }

    #[test]
    fn a_protracker_position_jump_clears_a_break_row_an_earlier_channel_chose() {
        let mut protracker = state(ModLoopDialect::ProTracker.flow());
        protracker.begin_row();
        protracker.pattern_break(12);
        protracker.pattern_jump(3);
        assert_eq!(protracker.jump(), Some(Jump::to_order_row(3, 0)));

        let mut scream = state(S3mLoopDialect::ScreamTracker321.flow());
        scream.begin_row();
        scream.pattern_break(12);
        scream.pattern_jump(3);
        assert_eq!(scream.jump(), Some(Jump::to_order_row(3, 12)), "ST3 keeps the break row");
    }

    #[test]
    fn a_seek_drops_every_target_and_counter() {
        let mut flow = state(S3mLoopDialect::ScreamTracker321.flow());
        flow.begin_row();
        flow.pattern_loop(0, 4, 0);
        flow.pattern_loop(0, 8, 3);
        flow.reset();
        assert_eq!(flow.count(0), 0);
        assert_eq!(flow.start(0), 0);
        assert_eq!(flow.jump(), None);
    }
}
