[package]
name = "starplayer-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
starplayer-core = { workspace = true }
starplayer-rt = { workspace = true }

[features]
default = []
std = ["starplayer-core/std", "starplayer-rt/std"]
alloc = ["starplayer-core/alloc", "starplayer-rt/alloc"]
serde = ["starplayer-core/serde"]
