//! Synthesised MOD, MTM, XM and IT golden fixtures.
//!
//! # Why generated bytes rather than a committed module
//!
//! C6's golden corpus is S3Ms the repository owner wrote, so their bytes can be
//! committed. There is no equivalent licence-safe MOD or MTM, and M2's exit criterion 4
//! wants a cross-target hash for the two formats this milestone adds. Task C6a offered two
//! routes: hash renders of the pinned libxmp corpus inside the conformance job, or
//! synthesise fixtures here and commit the generator instead of the module.
//!
//! This is the second route. It costs a few hundred lines, and it buys three things the
//! corpus route cannot:
//!
//! * The golden job needs no corpus, no network and no cache, so it runs identically on
//!   x86-64, on the ARM64 runner and under Wasmtime — which is precisely where the
//!   cross-target hash equality claim has to hold.
//! * Repinning the libxmp corpus revision cannot silently move a hash.
//! * The fixture's content is chosen rather than found: every cell below exists to reach
//!   a specific mixer or effect path (a looped sample, both finetune directions, vibrato,
//!   panning, a speed change and a BPM change), so a hash break points somewhere.
//!
//! The cost is that these modules were never played by a real tracker, so the hash is a
//! *regression* contract, not an accuracy one. Accuracy is the conformance harness's job
//! against libxmp; this is the "did the mixer change?" alarm.
//!
//! Both generators are pure functions of nothing, so the bytes are identical on every
//! host and every run.

use starplayer::mod_file::ModCell;
use starplayer::mtm::MtmCell;
use starplayer::xm::XmCell;

/// Channels in both synthesised fixtures.
const CHANNELS: usize = 4;
/// Rows per pattern in both formats.
const ROWS: usize = 64;
/// Patterns in both synthesised fixtures. Two orders at speed 6 cover the whole
/// ten-second golden segment without relying on the sequencer's end-of-song loop.
const PATTERNS: usize = 2;

const MOD_HEADER_BYTES: usize = 1084;
const MOD_SAMPLE_SLOTS: usize = 31;
const MOD_SAMPLE_HEADER_BYTES: usize = 30;
const MOD_CELL_BYTES: usize = 4;

const MTM_HEADER_BYTES: usize = 66;
const MTM_SAMPLE_HEADER_BYTES: usize = 37;
const MTM_ORDER_BYTES: usize = 128;
const MTM_CELL_BYTES: usize = 3;
const MTM_TRACK_BYTES: usize = ROWS * MTM_CELL_BYTES;
const MTM_PATTERN_TABLE_BYTES: usize = 32 * 2;

/// Bytes of XM header that follow the `headerSize` field itself.
const XM_HEADER_SIZE: usize = 276;
/// Where the `headerSize` field lives, and therefore where `headerSize` is measured from.
const XM_HEADER_SIZE_OFFSET: usize = 60;
/// Bytes of a full FastTracker 2 instrument header.
const XM_INSTRUMENT_HEADER_BYTES: usize = 263;
/// Bytes of one XM sample header.
const XM_SAMPLE_HEADER_BYTES: usize = 40;

// The fixed ProTracker header is a title, 31 sample headers, then the song length byte.
// Stating that as a compile-time identity keeps the constants above honest about the
// literal offsets the writers below use.
const _: () = assert!(20 + MOD_SAMPLE_SLOTS * MOD_SAMPLE_HEADER_BYTES == 950);
const _: () = assert!(950 + 2 + 128 + 4 == MOD_HEADER_BYTES);
const _: () = assert!(MTM_TRACK_BYTES == ROWS * MTM_CELL_BYTES);

/// A looped 128-frame ramp. The loop is the whole sample, so every voice that reaches the
/// end of it re-enters the mixer's loop path rather than stopping.
fn looped_ramp() -> Vec<i8> {
    (0..128).map(|index: i32| (index * 2 - 127) as i8).collect()
}

/// The same ramp stretched over 512 frames, so a `9xx`/`Oxx` parameter of `01` — 256
/// source frames — lands **inside** the sample rather than past its end.
///
/// Only the enhancer fixtures use it: every committed golden keeps the 128-frame ramp
/// above, because changing a golden fixture's bytes changes its hash.
fn long_looped_ramp() -> Vec<i8> {
    (0..512).map(|index: i32| ((index / 4) * 2 - 127) as i8).collect()
}

/// A one-shot 64-frame two-level pulse. Its hard edges make an interpolation change
/// visible in the hash rather than dissolving into a smooth waveform.
fn one_shot_pulse() -> Vec<i8> {
    (0..64).map(|index: i32| if (index / 8) % 2 == 0 { 100 } else { -100 }).collect()
}

/// ProTracker periods for the notes used below, all inside the 113..=856 Amiga range so
/// the loader keeps `amiga_limits` on and the clamp path stays exercised.
const C2: u16 = 428;
const E2: u16 = 339;
const G2: u16 = 285;
const C3: u16 = 214;
const A2: u16 = 254;

/// A four-channel M.K. module exercising loops, both finetune directions, vibrato,
/// panning, tone portamento, a volume slide, a speed change and a BPM change.
///
/// The layout is the ordinary 31-sample ProTracker one: a 1084-byte fixed header, then
/// `PATTERNS` patterns of 64 rows × 4 channels × 4 bytes, then sample PCM in slot order.
pub fn synthetic_mod() -> Vec<u8> {
    let looped = looped_ramp();
    let pulse = one_shot_pulse();

    let mut bytes = vec![0u8; MOD_HEADER_BYTES];
    write_text(&mut bytes[..20], "starplayer synth");

    // Slot one: looped, finetune +1. Slot two: one-shot, finetune -1 (nibble 15).
    write_mod_sample_header(&mut bytes, 0, "looped ramp", looped.len(), Some((0, looped.len())), 1, 64);
    write_mod_sample_header(&mut bytes, 1, "one-shot pulse", pulse.len(), None, 15, 48);

    bytes[950] = PATTERNS as u8;
    bytes[951] = 0;
    for order in 0..PATTERNS { bytes[952 + order] = order as u8; }
    bytes[1080..1084].copy_from_slice(b"M.K.");

    let mut patterns = vec![[ModCell::EMPTY; CHANNELS]; ROWS * PATTERNS];
    let mut cell = |pattern: usize, row: usize, channel: usize, value: ModCell| {
        patterns[pattern * ROWS + row][channel] = value;
    };

    // ── pattern 0: every voice starts, then one effect class per channel ────────────
    cell(0, 0, 0, ModCell { period: C2, instrument: 1, effect: 0, param: 0 });
    cell(0, 0, 1, ModCell { period: E2, instrument: 2, effect: 0x8, param: 0x30 });
    cell(0, 0, 2, ModCell { period: G2, instrument: 1, effect: 0x8, param: 0xC0 });
    cell(0, 0, 3, ModCell { period: A2, instrument: 2, effect: 0xC, param: 0x28 });
    // Vibrato on the looped voice, held over the following rows by a bare 4xy.
    cell(0, 4, 0, ModCell { period: 0, instrument: 0, effect: 0x4, param: 0x84 });
    cell(0, 5, 0, ModCell { period: 0, instrument: 0, effect: 0x4, param: 0x00 });
    cell(0, 6, 0, ModCell { period: 0, instrument: 0, effect: 0x4, param: 0x00 });
    // Volume slide down, then up, on the finetuned one-shot voice.
    cell(0, 8, 1, ModCell { period: 0, instrument: 0, effect: 0xA, param: 0x03 });
    cell(0, 12, 1, ModCell { period: 0, instrument: 0, effect: 0xA, param: 0x40 });
    // Tone portamento towards C-3 with its own slide continuation.
    cell(0, 16, 2, ModCell { period: C3, instrument: 0, effect: 0x3, param: 0x10 });
    cell(0, 17, 2, ModCell { period: 0, instrument: 0, effect: 0x3, param: 0x00 });
    // Speed change, then a BPM change eight rows later; both are Fxx on channel three.
    cell(0, 24, 3, ModCell { period: 0, instrument: 0, effect: 0xF, param: 0x03 });
    cell(0, 32, 3, ModCell { period: 0, instrument: 0, effect: 0xF, param: 0x96 });
    // Retrigger the looped sample from a sample offset so the loop is entered mid-way.
    cell(0, 40, 0, ModCell { period: C2, instrument: 1, effect: 0x9, param: 0x01 });
    // Extended commands: set finetune, then a fine volume slide.
    cell(0, 48, 1, ModCell { period: E2, instrument: 2, effect: 0xE, param: 0x57 });
    cell(0, 56, 1, ModCell { period: 0, instrument: 0, effect: 0xE, param: 0xA2 });

    // ── pattern 1: the same voices at different pitches, back to the default speed ──
    cell(1, 0, 0, ModCell { period: G2, instrument: 1, effect: 0xF, param: 0x06 });
    cell(1, 0, 1, ModCell { period: C3, instrument: 1, effect: 0x8, param: 0xFF });
    cell(1, 0, 2, ModCell { period: A2, instrument: 2, effect: 0x8, param: 0x00 });
    cell(1, 0, 3, ModCell { period: C2, instrument: 1, effect: 0xC, param: 0x40 });
    // Arpeggio, portamento up and portamento down, one per channel.
    cell(1, 8, 0, ModCell { period: 0, instrument: 0, effect: 0x0, param: 0x47 });
    cell(1, 16, 1, ModCell { period: 0, instrument: 0, effect: 0x1, param: 0x08 });
    cell(1, 24, 2, ModCell { period: 0, instrument: 0, effect: 0x2, param: 0x08 });
    // Tremolo, then a pattern-delay row, then a note cut.
    cell(1, 32, 3, ModCell { period: 0, instrument: 0, effect: 0x7, param: 0x62 });
    cell(1, 40, 0, ModCell { period: 0, instrument: 0, effect: 0xE, param: 0xE2 });
    cell(1, 48, 1, ModCell { period: 0, instrument: 0, effect: 0xE, param: 0xC3 });
    cell(1, 56, 2, ModCell { period: C2, instrument: 1, effect: 0x0, param: 0x00 });

    bytes.reserve(PATTERNS * ROWS * CHANNELS * MOD_CELL_BYTES + looped.len() + pulse.len());
    for row in patterns {
        for value in row {
            bytes.extend_from_slice(&value.to_bytes());
        }
    }
    bytes.extend(looped.iter().map(|sample| *sample as u8));
    bytes.extend(pulse.iter().map(|sample| *sample as u8));
    bytes
}

/// A four-channel MultiTracker module built from five shared tracks.
///
/// MTM's whole point is that patterns reference tracks, so pattern one reuses pattern
/// zero's tracks in a different channel order and swaps in one track of its own. Its pan
/// positions come from the header rather than from an effect, which is the other thing
/// that separates it from MOD.
pub fn synthetic_mtm() -> Vec<u8> {
    const TRACK_COUNT: usize = 5;
    let looped: Vec<u8> = looped_ramp().iter().map(|sample| (*sample as i16 + 128) as u8).collect();
    let pulse: Vec<u8> = one_shot_pulse().iter().map(|sample| (*sample as i16 + 128) as u8).collect();

    let mut header = vec![0u8; MTM_HEADER_BYTES];
    header[..4].copy_from_slice(b"MTM\x10");
    write_text(&mut header[4..24], "starplayer synth");
    header[24..26].copy_from_slice(&(TRACK_COUNT as u16).to_le_bytes());
    header[26] = (PATTERNS - 1) as u8;
    header[27] = (PATTERNS - 1) as u8;
    header[28..30].copy_from_slice(&0u16.to_le_bytes());
    header[30] = 2;
    header[31] = 0;
    header[32] = ROWS as u8;
    header[33] = CHANNELS as u8;
    // Header pan positions, 0..15 with 8 centred: wide, near-centre, near-centre, wide.
    header[34..38].copy_from_slice(&[0x00, 0x06, 0x0A, 0x0F]);

    let mut samples = Vec::new();
    samples.extend_from_slice(&mtm_sample_header("looped ramp", looped.len(), Some((0, looped.len())), 1, 64));
    samples.extend_from_slice(&mtm_sample_header("one-shot pulse", pulse.len(), None, 15, 48));

    let mut orders = vec![0u8; MTM_ORDER_BYTES];
    for (order, slot) in orders.iter_mut().take(PATTERNS).enumerate() { *slot = order as u8; }

    // Track one: the looped voice, vibrato and a sample-offset retrigger.
    let mut tracks = vec![MtmCell::EMPTY; TRACK_COUNT * ROWS];
    let mut cell = |track: usize, row: usize, value: MtmCell| {
        tracks[(track - 1) * ROWS + row] = value;
    };
    cell(1, 0, MtmCell { pitch: 25, instrument: 1, effect: 0, param: 0 });
    cell(1, 4, MtmCell { pitch: 0, instrument: 0, effect: 0x4, param: 0x84 });
    cell(1, 5, MtmCell { pitch: 0, instrument: 0, effect: 0x4, param: 0x00 });
    cell(1, 40, MtmCell { pitch: 25, instrument: 1, effect: 0x9, param: 0x01 });

    // Track two: the finetuned one-shot, volume slides both ways.
    cell(2, 0, MtmCell { pitch: 29, instrument: 2, effect: 0xC, param: 0x30 });
    cell(2, 8, MtmCell { pitch: 0, instrument: 0, effect: 0xA, param: 0x03 });
    cell(2, 12, MtmCell { pitch: 0, instrument: 0, effect: 0xA, param: 0x40 });
    cell(2, 48, MtmCell { pitch: 29, instrument: 2, effect: 0xE, param: 0x57 });

    // Track three: tone portamento and the extended fine slides.
    cell(3, 0, MtmCell { pitch: 32, instrument: 1, effect: 0, param: 0 });
    cell(3, 16, MtmCell { pitch: 37, instrument: 0, effect: 0x3, param: 0x10 });
    cell(3, 17, MtmCell { pitch: 0, instrument: 0, effect: 0x3, param: 0x00 });
    cell(3, 32, MtmCell { pitch: 0, instrument: 0, effect: 0xE, param: 0xA2 });

    // Track four: the timing track — a speed change and then a BPM change.
    cell(4, 0, MtmCell { pitch: 20, instrument: 2, effect: 0xC, param: 0x28 });
    cell(4, 24, MtmCell { pitch: 0, instrument: 0, effect: 0xF, param: 0x03 });
    cell(4, 32, MtmCell { pitch: 0, instrument: 0, effect: 0xF, param: 0x96 });
    cell(4, 56, MtmCell { pitch: 0, instrument: 0, effect: 0x7, param: 0x62 });

    // Track five: pattern one's own timing track, returning to the default speed.
    cell(5, 0, MtmCell { pitch: 20, instrument: 1, effect: 0xF, param: 0x06 });
    cell(5, 8, MtmCell { pitch: 0, instrument: 0, effect: 0x0, param: 0x47 });
    cell(5, 16, MtmCell { pitch: 0, instrument: 0, effect: 0x1, param: 0x08 });
    cell(5, 24, MtmCell { pitch: 0, instrument: 0, effect: 0x2, param: 0x08 });
    cell(5, 40, MtmCell { pitch: 0, instrument: 0, effect: 0xE, param: 0xC3 });

    // Pattern zero plays tracks 1..4 in order; pattern one rotates them and swaps the
    // timing track, so the same tracks are heard through different channel pans.
    let pattern_tracks: [[u16; CHANNELS]; PATTERNS] = [
        [1, 2, 3, 4],
        [3, 1, 2, 5],
    ];

    let mut bytes = Vec::with_capacity(
        MTM_HEADER_BYTES + 2 * MTM_SAMPLE_HEADER_BYTES + MTM_ORDER_BYTES
            + TRACK_COUNT * MTM_TRACK_BYTES + PATTERNS * MTM_PATTERN_TABLE_BYTES + looped.len() + pulse.len(),
    );
    bytes.extend_from_slice(&header);
    bytes.extend_from_slice(&samples);
    bytes.extend_from_slice(&orders);
    for value in &tracks {
        bytes.extend_from_slice(&value.to_bytes());
    }
    for pattern in pattern_tracks {
        let mut table = vec![0u8; MTM_PATTERN_TABLE_BYTES];
        for (channel, track) in pattern.iter().enumerate() {
            table[channel * 2..channel * 2 + 2].copy_from_slice(&track.to_le_bytes());
        }
        bytes.extend_from_slice(&table);
    }
    bytes.extend_from_slice(&looped);
    bytes.extend_from_slice(&pulse);
    bytes
}

/// A four-channel FastTracker 2 module in linear-frequency mode, with one instrument that
/// owns **two** samples through its note→sample map, both envelopes on, a sustain point, a
/// ping-pong loop, a key-off and a fadeout.
///
/// Every one of those is a path no MOD or MTM fixture can reach, which is the whole reason
/// this generator exists rather than a second `.mod`: the golden hash is the alarm that
/// says the XM articulation path changed.
pub fn synthetic_xm() -> Vec<u8> {
    let looped = looped_ramp();
    let pulse = one_shot_pulse();

    let mut bytes = Vec::new();
    bytes.extend_from_slice(b"Extended Module: ");
    let mut name = [b' '; 20];
    write_text(&mut name, "starplayer synth");
    bytes.extend_from_slice(&name);
    bytes.push(0x1A);
    let mut tracker = [b' '; 20];
    write_text(&mut tracker, "FastTracker v2.00");
    bytes.extend_from_slice(&tracker);
    bytes.extend_from_slice(&0x0104u16.to_le_bytes());

    let mut header = [0u8; XM_HEADER_SIZE];
    header[0x00..0x04].copy_from_slice(&(XM_HEADER_SIZE as u32).to_le_bytes());
    header[0x04..0x06].copy_from_slice(&(PATTERNS as u16).to_le_bytes());
    header[0x06..0x08].copy_from_slice(&0u16.to_le_bytes());
    header[0x08..0x0A].copy_from_slice(&(CHANNELS as u16).to_le_bytes());
    header[0x0A..0x0C].copy_from_slice(&(PATTERNS as u16).to_le_bytes());
    header[0x0C..0x0E].copy_from_slice(&1u16.to_le_bytes());
    // Bit 0: linear frequencies, which is what this fixture exists to exercise.
    header[0x0E..0x10].copy_from_slice(&1u16.to_le_bytes());
    header[0x10..0x12].copy_from_slice(&6u16.to_le_bytes());
    header[0x12..0x14].copy_from_slice(&125u16.to_le_bytes());
    for order in 0..PATTERNS {
        header[0x14 + order] = order as u8;
    }
    bytes.extend_from_slice(&header);
    debug_assert_eq!(bytes.len(), XM_HEADER_SIZE_OFFSET + XM_HEADER_SIZE);

    for pattern in 0..PATTERNS {
        bytes.extend_from_slice(&xm_pattern(pattern));
    }
    bytes.extend_from_slice(&xm_instrument(&looped, &pulse));
    bytes
}

/// One pattern, written as an unpacked five-byte-per-cell stream so the generator stays
/// readable — a legal XM, because a byte with bit 7 clear is a note followed by all four
/// remaining columns.
fn xm_pattern(pattern: usize) -> Vec<u8> {
    let mut cells = vec![XmCell::EMPTY; ROWS * CHANNELS];
    let mut cell = |row: usize, channel: usize, value: XmCell| {
        cells[row * CHANNELS + channel] = value;
    };

    // Channel one: the ping-pong sample, held through its sustain point, then keyed off so
    // the volume envelope releases and the fadeout runs.
    cell(0, 0, XmCell { note: 49, instrument: 1, volume: 0, effect: 0, parameter: 0 });
    cell(16, 0, XmCell { note: 0, instrument: 0, volume: 0, effect: 0x04, parameter: 0x83 });
    cell(32, 0, XmCell { note: 97, instrument: 0, volume: 0, effect: 0, parameter: 0 });
    cell(40, 0, XmCell { note: 49, instrument: 1, volume: 0x30, effect: 0, parameter: 0 });

    // Channel two: the one-shot the note→sample map selects two octaves up, with a tone
    // portamento and the volume column's own slide.
    cell(0, 1, XmCell { note: 73, instrument: 1, volume: 0x40, effect: 0, parameter: 0 });
    cell(8, 1, XmCell { note: 78, instrument: 0, volume: 0, effect: 0x03, parameter: 0x08 });
    cell(9, 1, XmCell { note: 0, instrument: 0, volume: 0, effect: 0x03, parameter: 0x00 });
    cell(24, 1, XmCell { note: 0, instrument: 0, volume: 0x63, effect: 0, parameter: 0 });
    cell(48, 1, XmCell { note: 73, instrument: 1, volume: 0, effect: 0x09, parameter: 0x08 });

    // Channel three: panning — the envelope, `8xx` and the volume column's pan slide.
    cell(0, 2, XmCell { note: 61, instrument: 1, volume: 0, effect: 0x08, parameter: 0x20 });
    cell(12, 2, XmCell { note: 0, instrument: 0, volume: 0xD4, effect: 0, parameter: 0 });
    cell(20, 2, XmCell { note: 0, instrument: 0, volume: 0xE4, effect: 0, parameter: 0 });
    cell(36, 2, XmCell { note: 0, instrument: 0, volume: 0, effect: 0x19, parameter: 0x40 });

    // Channel four: the timing track — arpeggio, a fine portamento, a speed change and a
    // BPM change, plus a tremor and a retrigger on the second pattern.
    cell(0, 3, XmCell { note: 37, instrument: 1, volume: 0x2A, effect: 0, parameter: 0 });
    cell(4, 3, XmCell { note: 0, instrument: 0, volume: 0, effect: 0x00, parameter: 0x47 });
    cell(16, 3, XmCell { note: 0, instrument: 0, volume: 0, effect: 0x0E, parameter: 0x12 });
    cell(24, 3, XmCell { note: 0, instrument: 0, volume: 0, effect: 0x0F, parameter: 0x03 });
    cell(32, 3, XmCell { note: 0, instrument: 0, volume: 0, effect: 0x0F, parameter: 0x96 });
    cell(48, 3, XmCell { note: 0, instrument: 0, volume: 0, effect: 0x0F, parameter: 0x06 });
    if pattern == 1 {
        cell(8, 3, XmCell { note: 0, instrument: 0, volume: 0, effect: 0x1D, parameter: 0x23 });
        cell(20, 3, XmCell { note: 37, instrument: 1, volume: 0, effect: 0x1B, parameter: 0x83 });
        cell(40, 3, XmCell { note: 0, instrument: 0, volume: 0, effect: 0x21, parameter: 0x14 });
    }

    let mut packed = Vec::with_capacity(cells.len() * 5);
    for cell in &cells {
        packed.extend_from_slice(&cell.to_bytes());
    }

    let mut pattern_bytes = Vec::with_capacity(9 + packed.len());
    pattern_bytes.extend_from_slice(&9u32.to_le_bytes());
    pattern_bytes.push(0);
    pattern_bytes.extend_from_slice(&(ROWS as u16).to_le_bytes());
    pattern_bytes.extend_from_slice(&(packed.len() as u16).to_le_bytes());
    pattern_bytes.extend_from_slice(&packed);
    pattern_bytes
}

/// The one instrument: two samples, a note→sample map that switches between them at C-5, a
/// three-point volume envelope with a sustain point and a loop, a two-point panning
/// envelope, a fadeout and an auto-vibrato.
fn xm_instrument(looped: &[i8], pulse: &[i8]) -> Vec<u8> {
    let mut header = [0u8; XM_INSTRUMENT_HEADER_BYTES];
    header[0x00..0x04].copy_from_slice(&(XM_INSTRUMENT_HEADER_BYTES as u32).to_le_bytes());
    write_text(&mut header[0x04..0x1A], "two samples");
    header[0x1B..0x1D].copy_from_slice(&2u16.to_le_bytes());
    header[0x1D..0x21].copy_from_slice(&(XM_SAMPLE_HEADER_BYTES as u32).to_le_bytes());
    // Notes below C-5 play the ping-pong ramp; C-5 and above play the one-shot pulse.
    for note in 0..96 {
        header[0x21 + note] = u8::from(note >= 60);
    }
    // Volume envelope: (0, 64) -> (12, 40) -> (48, 0), sustaining on the middle point and
    // looping the whole span, so a note that is never released holds and one that is
    // released falls away under the fadeout.
    for (index, (tick, value)) in [(0u16, 64u16), (12, 40), (48, 0)].into_iter().enumerate() {
        header[0x81 + index * 4..0x81 + index * 4 + 2].copy_from_slice(&tick.to_le_bytes());
        header[0x81 + index * 4 + 2..0x81 + index * 4 + 4].copy_from_slice(&value.to_le_bytes());
    }
    // Panning envelope: hard left to hard right over 24 ticks.
    for (index, (tick, value)) in [(0u16, 0u16), (24, 64)].into_iter().enumerate() {
        header[0xB1 + index * 4..0xB1 + index * 4 + 2].copy_from_slice(&tick.to_le_bytes());
        header[0xB1 + index * 4 + 2..0xB1 + index * 4 + 4].copy_from_slice(&value.to_le_bytes());
    }
    header[0xE1] = 3;
    header[0xE2] = 2;
    header[0xE3] = 1;
    header[0xE4] = 0;
    header[0xE5] = 2;
    header[0xE6] = 0;
    header[0xE7] = 0;
    header[0xE8] = 1;
    header[0xE9] = 1 | 2 | 4;
    header[0xEA] = 1;
    header[0xEB] = 0;
    header[0xEC] = 24;
    header[0xED] = 6;
    header[0xEE] = 4;
    header[0xEF..0xF1].copy_from_slice(&512u16.to_le_bytes());

    let mut bytes = Vec::new();
    bytes.extend_from_slice(&header);
    // Sample zero: the ramp, ping-pong looped over its whole length, transposed down an
    // octave and finetuned sharp.
    bytes.extend_from_slice(&xm_sample_header(XmSample {
        name: "ping-pong ramp",
        length: looped.len(),
        loop_span: Some((0, looped.len())),
        flags: 0x02,
        volume: 64,
        pan: 0x20,
        relative_note: -12,
        finetune: 32,
    }));
    // Sample one: the pulse, one-shot, transposed up and finetuned flat.
    bytes.extend_from_slice(&xm_sample_header(XmSample {
        name: "one-shot pulse",
        length: pulse.len(),
        loop_span: None,
        flags: 0x00,
        volume: 48,
        pan: 0xE0,
        relative_note: 7,
        finetune: -40,
    }));
    bytes.extend_from_slice(&delta_encode(looped));
    bytes.extend_from_slice(&delta_encode(pulse));
    bytes
}

/// One 40-byte XM sample header. The fields are a struct rather than eight positional
/// arguments so that a caller cannot silently swap the pan byte for the volume one.
struct XmSample<'name> {
    name: &'name str,
    length: usize,
    loop_span: Option<(usize, usize)>,
    flags: u8,
    volume: u8,
    pan: u8,
    relative_note: i8,
    finetune: i8,
}

fn xm_sample_header(sample: XmSample<'_>) -> [u8; XM_SAMPLE_HEADER_BYTES] {
    let XmSample { name, length, loop_span, flags, volume, pan, relative_note, finetune } = sample;
    let mut header = [0u8; XM_SAMPLE_HEADER_BYTES];
    header[0x00..0x04].copy_from_slice(&(length as u32).to_le_bytes());
    let (loop_start, loop_length) = loop_span.map(|(start, end)| (start, end - start)).unwrap_or((0, 0));
    header[0x04..0x08].copy_from_slice(&(loop_start as u32).to_le_bytes());
    header[0x08..0x0C].copy_from_slice(&(loop_length as u32).to_le_bytes());
    header[0x0C] = volume;
    header[0x0D] = finetune as u8;
    header[0x0E] = flags;
    header[0x0F] = pan;
    header[0x10] = relative_note as u8;
    header[0x11] = 0;
    write_text(&mut header[0x12..0x28], name);
    header
}

/// XM stores eight-bit PCM as signed deltas.
fn delta_encode(samples: &[i8]) -> Vec<u8> {
    let mut previous = 0i8;
    samples.iter().map(|sample| {
        let delta = sample.wrapping_sub(previous);
        previous = *sample;
        delta as u8
    }).collect()
}

/// A four-channel Impulse Tracker module in **instrument mode**, with two samples, two
/// instruments, all three envelopes, a sustain loop and a New Note Action of `Continue`.
///
/// The pattern is written to reach the paths that make IT different from S3M rather than
/// to sound like music: repeated notes on one channel so the `Continue` instrument leaves
/// background voices running, a `Gxx` portamento, a `Dxy` volume slide, an `Hxy` vibrato,
/// a channel-volume `Mxx`, an `Xxx` pan and a `Qxy` retrigger. No `Zxx`: the filter is
/// task G2's, and a golden that changed the moment the filter landed would be useless as
/// a regression alarm for the mixer.
pub fn synthetic_it() -> Vec<u8> { synthetic_it_with(looped_ramp(), false) }

/// The same IT with a 512-frame looped sample and an `Oxx` that lands inside it.
///
/// A separate fixture rather than a change to [`synthetic_it`], because the committed IT
/// golden hashes that generator's bytes. M10-K5a's trace-position proof needs a module
/// whose sample-offset command is **in range**, and every other synthetic fixture's
/// samples are shorter than the 256 frames the smallest non-zero parameter asks for.
pub fn synthetic_it_with_offset() -> Vec<u8> { synthetic_it_with(long_looped_ramp(), true) }

fn synthetic_it_with(ramp: Vec<i8>, offsets: bool) -> Vec<u8> {
    const IT_ROWS: usize = 32;
    const IT_CHANNELS: usize = 4;
    const HEADER_BYTES: usize = 0xC0;
    const INSTRUMENT_BYTES: usize = 554;
    const SAMPLE_BYTES: usize = 80;
    const ORDERS: [u8; 2] = [0, 255];

    let looped: Vec<u8> = ramp.iter().map(|sample| (*sample as i16 + 128) as u8).collect();
    let pulse: Vec<u8> = one_shot_pulse().iter().map(|sample| (*sample as i16 + 128) as u8).collect();

    let pattern = it_pattern(IT_ROWS, offsets);
    let orders_offset = HEADER_BYTES;
    let instrument_offsets_offset = orders_offset + ORDERS.len();
    let sample_offsets_offset = instrument_offsets_offset + 2 * 4;
    let pattern_offsets_offset = sample_offsets_offset + 2 * 4;
    let instruments_offset = pattern_offsets_offset + 4;
    let samples_offset = instruments_offset + 2 * INSTRUMENT_BYTES;
    let patterns_offset = samples_offset + 2 * SAMPLE_BYTES;
    let first_pcm_offset = patterns_offset + pattern.len();
    let second_pcm_offset = first_pcm_offset + looped.len();

    let mut bytes = vec![0u8; second_pcm_offset + pulse.len()];
    bytes[..4].copy_from_slice(b"IMPM");
    write_text(&mut bytes[4..30], "starplayer synth it");
    bytes[0x20..0x22].copy_from_slice(&(ORDERS.len() as u16).to_le_bytes());
    bytes[0x22..0x24].copy_from_slice(&2u16.to_le_bytes());
    bytes[0x24..0x26].copy_from_slice(&2u16.to_le_bytes());
    bytes[0x26..0x28].copy_from_slice(&1u16.to_le_bytes());
    bytes[0x28..0x2A].copy_from_slice(&0x0214u16.to_le_bytes());
    bytes[0x2A..0x2C].copy_from_slice(&0x0214u16.to_le_bytes());
    // Stereo, instrument mode, linear slides.
    bytes[0x2C..0x2E].copy_from_slice(&0x000Du16.to_le_bytes());
    bytes[0x2E..0x30].copy_from_slice(&0u16.to_le_bytes());
    bytes[0x30] = 128;
    bytes[0x31] = 48;
    bytes[0x32] = 6;
    bytes[0x33] = 125;
    bytes[0x34] = 128;
    bytes[0x35] = 0;
    for channel in 0..64 {
        bytes[0x40 + channel] = if channel < IT_CHANNELS { [16, 48, 24, 40][channel] } else { 32 };
        bytes[0x80 + channel] = 64;
    }
    bytes[orders_offset..orders_offset + ORDERS.len()].copy_from_slice(&ORDERS);
    for (index, offset) in [instruments_offset, instruments_offset + INSTRUMENT_BYTES].into_iter().enumerate() {
        let at = instrument_offsets_offset + index * 4;
        bytes[at..at + 4].copy_from_slice(&(offset as u32).to_le_bytes());
    }
    for (index, offset) in [samples_offset, samples_offset + SAMPLE_BYTES].into_iter().enumerate() {
        let at = sample_offsets_offset + index * 4;
        bytes[at..at + 4].copy_from_slice(&(offset as u32).to_le_bytes());
    }
    bytes[pattern_offsets_offset..pattern_offsets_offset + 4].copy_from_slice(&(patterns_offset as u32).to_le_bytes());

    write_it_instrument(&mut bytes[instruments_offset..instruments_offset + INSTRUMENT_BYTES], 1, 1, true);
    write_it_instrument(&mut bytes[instruments_offset + INSTRUMENT_BYTES..instruments_offset + 2 * INSTRUMENT_BYTES], 2, 0, false);
    // The offset fixture's looped sample has **no** sustain loop: releasing one truncates
    // the voice's position to a whole frame (`SusAfterLoop.it`), and a whole frame of a
    // quadrupled sample is a quarter of a whole frame of the original, so the exact
    // position-scaling proof would have nothing to say about that one tick.
    write_it_sample(&mut bytes[samples_offset..samples_offset + SAMPLE_BYTES], looped.len() as u32, true, !offsets, first_pcm_offset as u32, 8_363);
    write_it_sample(
        &mut bytes[samples_offset + SAMPLE_BYTES..samples_offset + 2 * SAMPLE_BYTES],
        pulse.len() as u32,
        false,
        false,
        second_pcm_offset as u32,
        16_726,
    );
    bytes[patterns_offset..patterns_offset + pattern.len()].copy_from_slice(&pattern);
    bytes[first_pcm_offset..first_pcm_offset + looped.len()].copy_from_slice(&looped);
    bytes[second_pcm_offset..second_pcm_offset + pulse.len()].copy_from_slice(&pulse);
    bytes
}

/// One IT instrument header: a full keyboard map onto `sample`, the given New Note Action,
/// and either all three envelopes or a volume envelope alone.
fn write_it_instrument(destination: &mut [u8], sample: u8, new_note_action: u8, all_envelopes: bool) {
    destination[..4].copy_from_slice(b"IMPI");
    destination[0x11] = new_note_action;
    // Duplicate check on the note, duplicate action note-off, so the DCT path is reached.
    destination[0x12] = 1;
    destination[0x13] = 1;
    destination[0x14..0x16].copy_from_slice(&256u16.to_le_bytes());
    destination[0x16] = 8;
    destination[0x17] = 60;
    destination[0x18] = 128;
    destination[0x19] = 0x80;
    destination[0x1C..0x1E].copy_from_slice(&0x0214u16.to_le_bytes());
    destination[0x1E] = 1;
    write_text(&mut destination[0x20..0x3A], "synth instrument");
    for note in 0..120usize {
        destination[0x40 + note * 2] = note as u8;
        destination[0x40 + note * 2 + 1] = sample;
    }
    // Volume envelope: on, sustained between nodes one and two, looping over nodes two
    // and three, so both spans are exercised.
    write_it_envelope(&mut destination[0x130..0x1B2], 0b0000_0111, (2, 3), (1, 2), &[(64, 0), (48, 8), (56, 16), (0, 40)]);
    if all_envelopes {
        write_it_envelope(&mut destination[0x182..0x1D4], 0b0000_0001, (0, 0), (0, 0), &[(-24, 0), (24, 24)]);
        write_it_envelope(&mut destination[0x1D4..0x226], 0b0000_0001, (0, 0), (0, 0), &[(0, 0), (8, 12), (-8, 32)]);
    }
}

/// One 82-byte IT envelope structure.
fn write_it_envelope(destination: &mut [u8], flags: u8, loop_span: (u8, u8), sustain: (u8, u8), nodes: &[(i8, u16)]) {
    destination[0] = flags;
    destination[1] = nodes.len() as u8;
    destination[2] = loop_span.0;
    destination[3] = loop_span.1;
    destination[4] = sustain.0;
    destination[5] = sustain.1;
    for (index, (value, tick)) in nodes.iter().enumerate() {
        let at = 6 + index * 3;
        destination[at] = *value as u8;
        destination[at + 1..at + 3].copy_from_slice(&tick.to_le_bytes());
    }
}

/// One 80-byte IT sample header.
fn write_it_sample(destination: &mut [u8], length: u32, loops: bool, sustains: bool, pcm_offset: u32, c5_speed: u32) {
    destination[..4].copy_from_slice(b"IMPS");
    destination[0x11] = 64;
    // Has data, and — for the looped one — a forward loop, plus a forward sustain loop
    // unless the caller asked for the loop alone.
    destination[0x12] = 0x01 | if loops { 0x10 } else { 0 } | if sustains { 0x20 } else { 0 };
    destination[0x13] = 64;
    write_text(&mut destination[0x14..0x2E], "synth sample");
    // Unsigned PCM, as Impulse Tracker 1.x wrote it.
    destination[0x2E] = 0;
    destination[0x2F] = 0;
    destination[0x30..0x34].copy_from_slice(&length.to_le_bytes());
    if loops {
        destination[0x34..0x38].copy_from_slice(&(length / 2).to_le_bytes());
        destination[0x38..0x3C].copy_from_slice(&length.to_le_bytes());
    }
    if sustains {
        destination[0x40..0x44].copy_from_slice(&(length / 4).to_le_bytes());
        destination[0x44..0x48].copy_from_slice(&(length / 2).to_le_bytes());
    }
    destination[0x3C..0x40].copy_from_slice(&c5_speed.to_le_bytes());
    destination[0x48..0x4C].copy_from_slice(&pcm_offset.to_le_bytes());
    // Auto-vibrato: a slow sine that sweeps in, so the per-sample path is reached.
    destination[0x4C] = 8;
    destination[0x4D] = 6;
    destination[0x4E] = 2;
    destination[0x4F] = 0;
}

/// The synthetic pattern, in IT's packed encoding.
fn it_pattern(rows: usize, offsets: bool) -> Vec<u8> {
    let mut packed = Vec::new();
    for row in 0..rows {
        for channel in 0..4u8 {
            let cell = it_cell(row, channel, offsets);
            let Some((note, instrument, volume, command, parameter)) = cell else { continue };
            let mut mask = 0u8;
            if note.is_some() { mask |= 0x01; }
            if instrument.is_some() { mask |= 0x02; }
            if volume.is_some() { mask |= 0x04; }
            if command.is_some() { mask |= 0x08; }
            packed.push((channel + 1) | 0x80);
            packed.push(mask);
            if let Some(note) = note { packed.push(note); }
            if let Some(instrument) = instrument { packed.push(instrument); }
            if let Some(volume) = volume { packed.push(volume); }
            if let Some(command) = command {
                packed.push(command);
                packed.push(parameter);
            }
        }
        packed.push(0);
    }
    let mut bytes = Vec::with_capacity(8 + packed.len());
    bytes.extend_from_slice(&(packed.len() as u16).to_le_bytes());
    bytes.extend_from_slice(&(rows as u16).to_le_bytes());
    bytes.extend_from_slice(&[0, 0, 0, 0]);
    bytes.extend_from_slice(&packed);
    bytes
}

/// One cell of the synthetic pattern: `(note, instrument, volume, command, parameter)`.
#[allow(clippy::type_complexity)]
fn it_cell(row: usize, channel: u8, offsets: bool) -> Option<(Option<u8>, Option<u8>, Option<u8>, Option<u8>, u8)> {
    let command = |letter: u8, parameter: u8| (Some(letter - b'A' + 1), parameter);
    match (channel, row) {
        // Channel zero: a `Continue` instrument retriggered every four rows, so background
        // voices pile up and the New Note Action, the duplicate check and the voice pool
        // are all exercised.
        (0, row) if row % 4 == 0 => Some((Some(48 + (row / 4) as u8), Some(1), None, None, 0)),
        (0, 3) => Some((None, None, Some(40), None, 0)),
        // Channel one: a note, then a tone portamento up to it, then a volume slide. The
        // `Oxx` at row eight exists only in the offset fixture, whose looped sample is
        // long enough for the smallest non-zero parameter to land inside it.
        (1, 8) if offsets => {
            let (letter, parameter) = command(b'O', 0x01);
            Some((Some(60), Some(1), None, letter, parameter))
        }
        (1, 0) => Some((Some(60), Some(1), None, None, 0)),
        (1, 4) => {
            let (letter, parameter) = command(b'G', 0x08);
            Some((Some(72), None, None, letter, parameter))
        }
        (1, 12) => {
            let (letter, parameter) = command(b'D', 0x04);
            Some((None, None, None, letter, parameter))
        }
        (1, 20) => Some((Some(255), None, None, None, 0)),
        // Channel two: the one-shot instrument with a vibrato and a channel volume.
        (2, 0) => {
            let (letter, parameter) = command(b'M', 0x30);
            Some((Some(60), Some(2), None, letter, parameter))
        }
        (2, 8) => {
            let (letter, parameter) = command(b'H', 0x84);
            Some((Some(55), Some(2), None, letter, parameter))
        }
        (2, 16) => {
            let (letter, parameter) = command(b'Q', 0x23);
            Some((Some(67), Some(2), None, letter, parameter))
        }
        // Channel three: panning and a fine pitch slide.
        (3, 0) => {
            let (letter, parameter) = command(b'X', 0x20);
            Some((Some(36), Some(1), Some(48), letter, parameter))
        }
        (3, 8) => {
            let (letter, parameter) = command(b'F', 0xF4);
            Some((None, None, None, letter, parameter))
        }
        (3, 24) => Some((Some(254), None, None, None, 0)),
        _ => None,
    }
}

fn write_text(destination: &mut [u8], text: &str) {
    let length = text.len().min(destination.len());
    destination[..length].copy_from_slice(&text.as_bytes()[..length]);
}

/// One 30-byte ProTracker sample header: name, big-endian word length, finetune nibble,
/// volume, and a big-endian word loop start and length.
fn write_mod_sample_header(bytes: &mut [u8], slot: usize, name: &str, length: usize, loop_span: Option<(usize, usize)>, finetune: u8, volume: u8) {
    let offset = 20 + slot * MOD_SAMPLE_HEADER_BYTES;
    let header = &mut bytes[offset..offset + MOD_SAMPLE_HEADER_BYTES];
    write_text(&mut header[..22], name);
    header[22..24].copy_from_slice(&((length / 2) as u16).to_be_bytes());
    header[24] = finetune & 15;
    header[25] = volume;
    let (loop_start, loop_length) = loop_span.unwrap_or((0, 2));
    header[26..28].copy_from_slice(&((loop_start / 2) as u16).to_be_bytes());
    header[28..30].copy_from_slice(&((loop_length / 2) as u16).to_be_bytes());
}

/// One 37-byte MultiTracker sample header: name, little-endian byte length, loop start
/// and end, finetune nibble, volume, and the 8/16-bit attribute byte.
fn mtm_sample_header(name: &str, length: usize, loop_span: Option<(usize, usize)>, finetune: u8, volume: u8) -> [u8; MTM_SAMPLE_HEADER_BYTES] {
    let mut header = [0u8; MTM_SAMPLE_HEADER_BYTES];
    write_text(&mut header[..22], name);
    header[22..26].copy_from_slice(&(length as u32).to_le_bytes());
    let (loop_start, loop_end) = loop_span.unwrap_or((0, 0));
    header[26..30].copy_from_slice(&(loop_start as u32).to_le_bytes());
    header[30..34].copy_from_slice(&(loop_end as u32).to_le_bytes());
    header[34] = finetune & 15;
    header[35] = volume;
    header[36] = 0;
    header
}

/// A one-channel, one-sample Impulse Tracker module carrying `frames` verbatim as a
/// signed 16-bit sample whose `C5Speed` is `rate_hz`, played once at note C-5 (M10-K5c).
///
/// # Why this exists
///
/// The enhancement harness has to compare a 44 100 Hz ground-truth instrument against the
/// 8 363 Hz, 8-bit version of the same instrument **through the real pipeline** rather
/// than by comparing two `Vec<i16>` in isolation, because an enhancer's output only means
/// anything after the mixer has resampled it to the output rate. IT is the format that
/// makes that possible: its `C5Speed` is an arbitrary rate, so a 44 100 Hz sample plays at
/// unity step against a 44 100 Hz render and the ground truth reaches the comparison
/// unresampled. Every other format's reference rate is either the Amiga clock or a fixed
/// 8 363.
///
/// The module is in **sample mode** — the instrument column names a sample directly — with
/// one channel, one 64-row pattern and a single order, so the render is one voice playing
/// one sample with nothing else in it: no envelopes, no auto-vibrato, no second note. Any
/// difference between two renders is the sample.
///
/// `loop_span` gives the sample a forward loop over `[start, end)`; `None` makes it a
/// one-shot. As the model requires, a forward loop's stored body must end at `loop_end`,
/// so the caller passes frames whose length is exactly the loop end.
pub fn synthetic_it_single_sample(frames: &[i16], rate_hz: u32, loop_span: Option<(u32, u32)>) -> Vec<u8> {
    const HEADER_BYTES: usize = 0xC0;
    const INSTRUMENT_BYTES: usize = 554;
    const SAMPLE_BYTES: usize = 80;
    const ORDERS: [u8; 2] = [0, 255];
    const IT_ROWS: usize = 64;

    let pattern = single_channel_it_pattern(IT_ROWS);
    let pcm: Vec<u8> = frames.iter().flat_map(|frame| frame.to_le_bytes()).collect();

    let orders_offset = HEADER_BYTES;
    let instrument_offsets_offset = orders_offset + ORDERS.len();
    let sample_offsets_offset = instrument_offsets_offset + 4;
    let pattern_offsets_offset = sample_offsets_offset + 4;
    let instruments_offset = pattern_offsets_offset + 4;
    let samples_offset = instruments_offset + INSTRUMENT_BYTES;
    let patterns_offset = samples_offset + SAMPLE_BYTES;
    let pcm_offset = patterns_offset + pattern.len();

    let mut bytes = vec![0u8; pcm_offset + pcm.len()];
    bytes[..4].copy_from_slice(b"IMPM");
    write_text(&mut bytes[4..30], "starplayer enhance probe");
    bytes[0x20..0x22].copy_from_slice(&(ORDERS.len() as u16).to_le_bytes());
    bytes[0x22..0x24].copy_from_slice(&1u16.to_le_bytes());
    bytes[0x24..0x26].copy_from_slice(&1u16.to_le_bytes());
    bytes[0x26..0x28].copy_from_slice(&1u16.to_le_bytes());
    bytes[0x28..0x2A].copy_from_slice(&0x0214u16.to_le_bytes());
    bytes[0x2A..0x2C].copy_from_slice(&0x0214u16.to_le_bytes());
    // Stereo and linear slides, **not** instrument mode: the instrument column names the
    // sample, so there is no envelope anywhere to shape the voice.
    bytes[0x2C..0x2E].copy_from_slice(&0x0009u16.to_le_bytes());
    bytes[0x2E..0x30].copy_from_slice(&0u16.to_le_bytes());
    bytes[0x30] = 128;
    // Mixing volume at the format's maximum, which puts a 0.9-full-scale sample's render
    // at about −3 dBFS. That matters because the harness's log-spectral distance is
    // floored at −60 dB **relative to full scale**: every decibel the render sits below
    // full scale is a decibel of the instrument's own decay that falls under the floor and
    // stops being measured at all. The engine's limiter is `Clamp` and the render is
    // checked for warnings, so the headroom is real rather than assumed.
    bytes[0x31] = 128;
    bytes[0x32] = 6;
    bytes[0x33] = 125;
    bytes[0x34] = 128;
    bytes[0x35] = 0;
    for channel in 0..64 {
        // Dead centre, so a mono downmix loses nothing to panning.
        bytes[0x40 + channel] = 32;
        bytes[0x80 + channel] = 64;
    }
    bytes[orders_offset..orders_offset + ORDERS.len()].copy_from_slice(&ORDERS);
    bytes[instrument_offsets_offset..instrument_offsets_offset + 4].copy_from_slice(&(instruments_offset as u32).to_le_bytes());
    bytes[sample_offsets_offset..sample_offsets_offset + 4].copy_from_slice(&(samples_offset as u32).to_le_bytes());
    bytes[pattern_offsets_offset..pattern_offsets_offset + 4].copy_from_slice(&(patterns_offset as u32).to_le_bytes());

    // Sample mode ignores the instrument table, but the header claims one instrument, so a
    // well-formed empty header keeps the file honest.
    bytes[instruments_offset..instruments_offset + 4].copy_from_slice(b"IMPI");

    write_it_sixteen_bit_sample(&mut bytes[samples_offset..samples_offset + SAMPLE_BYTES], frames.len() as u32, loop_span, pcm_offset as u32, rate_hz);
    bytes[patterns_offset..patterns_offset + pattern.len()].copy_from_slice(&pattern);
    bytes[pcm_offset..pcm_offset + pcm.len()].copy_from_slice(&pcm);
    bytes
}

/// One 80-byte IT sample header for signed little-endian 16-bit PCM, with no sustain loop
/// and no auto-vibrato.
fn write_it_sixteen_bit_sample(destination: &mut [u8], length: u32, loop_span: Option<(u32, u32)>, pcm_offset: u32, c5_speed: u32) {
    destination[..4].copy_from_slice(b"IMPS");
    // Global volume and default volume both at their maxima: nothing here may scale the
    // sample, because the harness compares levels.
    destination[0x11] = 64;
    destination[0x12] = 0x01 | 0x02 | if loop_span.is_some() { 0x10 } else { 0 };
    destination[0x13] = 64;
    write_text(&mut destination[0x14..0x2E], "probe");
    // Signed, little-endian, not delta — how IT 2.02 and later wrote 16-bit data.
    destination[0x2E] = 0x01;
    destination[0x2F] = 0;
    destination[0x30..0x34].copy_from_slice(&length.to_le_bytes());
    if let Some((start, end)) = loop_span {
        destination[0x34..0x38].copy_from_slice(&start.to_le_bytes());
        destination[0x38..0x3C].copy_from_slice(&end.to_le_bytes());
    }
    destination[0x3C..0x40].copy_from_slice(&c5_speed.to_le_bytes());
    destination[0x48..0x4C].copy_from_slice(&pcm_offset.to_le_bytes());
}

/// A one-channel pattern whose first row plays note C-5 of sample one at full volume and
/// whose remaining rows are empty.
fn single_channel_it_pattern(rows: usize) -> Vec<u8> {
    let mut packed = Vec::new();
    for row in 0..rows {
        if row == 0 {
            packed.push(1 | 0x80);
            // Note, instrument and volume present; no effect.
            packed.push(0x01 | 0x02 | 0x04);
            // 60 is C-5, the note `C5Speed` names the rate of.
            packed.push(60);
            packed.push(1);
            packed.push(64);
        }
        packed.push(0);
    }
    let mut bytes = Vec::with_capacity(8 + packed.len());
    bytes.extend_from_slice(&(packed.len() as u16).to_le_bytes());
    bytes.extend_from_slice(&(rows as u16).to_le_bytes());
    bytes.extend_from_slice(&[0, 0, 0, 0]);
    bytes.extend_from_slice(&packed);
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;

    use starplayer::model::ModuleFormat;

    #[test]
    fn the_generators_are_deterministic_and_sized_exactly() {
        assert_eq!(synthetic_mod(), synthetic_mod(), "the MOD generator is a pure function");
        assert_eq!(synthetic_mtm(), synthetic_mtm(), "the MTM generator is a pure function");
        assert_eq!(synthetic_mod().len(), MOD_HEADER_BYTES + PATTERNS * ROWS * CHANNELS * MOD_CELL_BYTES + 128 + 64);
        assert_eq!(
            synthetic_mtm().len(),
            MTM_HEADER_BYTES + 2 * MTM_SAMPLE_HEADER_BYTES + MTM_ORDER_BYTES + 5 * MTM_TRACK_BYTES + PATTERNS * MTM_PATTERN_TABLE_BYTES + 128 + 64,
        );
        assert_eq!(MOD_SAMPLE_SLOTS * MOD_SAMPLE_HEADER_BYTES + 20, 950, "the fixed MOD header still ends where the loader expects");
    }

    #[test]
    fn both_fixtures_load_through_their_native_format_crate() {
        let module = starplayer::mod_file::load(&synthetic_mod()).expect("the synthetic MOD loads");
        assert_eq!(module.header().format, ModuleFormat::Mod);
        assert_eq!(module.header().channel_count, CHANNELS as u8);
        assert_eq!(starplayer::probe(&synthetic_mod()), Some(ModuleFormat::Mod), "autodetection agrees");

        let module = starplayer::mtm::load(&synthetic_mtm()).expect("the synthetic MTM loads");
        assert_eq!(module.header().format, ModuleFormat::Mtm);
        assert_eq!(module.header().channel_count, CHANNELS as u8);
        assert_eq!(starplayer::probe(&synthetic_mtm()), Some(ModuleFormat::Mtm), "autodetection agrees");

        let module = starplayer::xm::load(&synthetic_xm()).expect("the synthetic XM loads");
        assert_eq!(module.header().format, ModuleFormat::Xm);
        assert_eq!(module.header().channel_count, CHANNELS as u8);
        assert_eq!(starplayer::probe(&synthetic_xm()), Some(ModuleFormat::Xm), "autodetection agrees");
    }

    #[test]
    fn the_synthetic_xm_reaches_the_articulation_paths_no_other_fixture_can() {
        let module = starplayer::xm::load(&synthetic_xm()).expect("the synthetic XM loads");
        assert!(module.header().flags.linear_slides, "the fixture is a linear-frequency module");

        let instrument = module.instrument(starplayer::model::InstrumentId(0)).expect("the one instrument");
        assert!(instrument.volume_envelope.is_some(), "the volume envelope is on");
        assert!(instrument.panning_envelope.is_some(), "the panning envelope is on");
        assert_eq!(instrument.volume_envelope.as_ref().and_then(|envelope| envelope.sustain).map(|span| span.start), Some(1), "and it sustains");
        assert_eq!(instrument.fadeout, 512, "a key-off has something to fade with");
        assert_ne!(instrument.note_sample_map[0], instrument.note_sample_map[60], "the map switches sample at C-5");

        let ping_pong = module.sample(starplayer::model::SampleId(0)).expect("sample zero");
        assert_eq!(ping_pong.loop_mode(), starplayer::model::LoopMode::PingPong);
        assert_eq!(ping_pong.relative_note(), -12);
        let one_shot = module.sample(starplayer::model::SampleId(1)).expect("sample one");
        assert_eq!(one_shot.loop_mode(), starplayer::model::LoopMode::None);
        assert_ne!(one_shot.finetune(), ping_pong.finetune(), "the two samples carry opposite finetunes");
    }

    #[test]
    fn the_fixtures_reach_the_paths_they_exist_to_cover() {
        let module = starplayer::mod_file::load(&synthetic_mod()).expect("the synthetic MOD loads");
        let looped = module.sample(starplayer::model::SampleId(0)).expect("slot one is present");
        assert_eq!(looped.loop_mode(), starplayer::model::LoopMode::Forward, "slot one loops");
        let one_shot = module.sample(starplayer::model::SampleId(1)).expect("slot two is present");
        assert_eq!(one_shot.loop_mode(), starplayer::model::LoopMode::None, "slot two is one-shot");
        assert_ne!(looped.reference_rate_hz(), one_shot.reference_rate_hz(), "the two slots carry opposite finetunes");

        let module = starplayer::mtm::load(&synthetic_mtm()).expect("the synthetic MTM loads");
        assert_eq!(starplayer::mtm::track_count(&module), Some(5), "all five tracks survive the load");
        let pans = module.header().default_pan.clone();
        assert_ne!(pans[0], pans[1], "the header pan positions are not all the same");
    }
}
