//! The **module image** (`.spmi`): a built [`Module`] serialised so that a device can map
//! it in flash and play it without copying a single sample frame into RAM (M8-I2).
//!
//! # Why a second format at all
//!
//! The loaders are not the problem — the *copy* is. A loader turns a file into a `Module`
//! whose PCM is decoded, widened to `i16`, pre-rolled and guard-padded; on a 4 MB-flash
//! ESP32 with a few hundred KB of DRAM that finished blob is exactly what must not be
//! allocated. So the loader runs on the development machine (`cargo xtask module-image`),
//! the finished `Module` is written out with its PCM 4-byte aligned, the image is linked
//! into the firmware, and [`Module::from_image`] borrows the PCM and the pattern blob in
//! place. A load becomes a validation pass and four small index allocations.
//!
//! A module *uploaded at run time* still goes through the ordinary loader into the heap.
//! Both paths produce the same `Module`; only the storage differs.
//!
//! # The layout
//!
//! Flat, little-endian, read front to back. Every length is a `u32` and every one of them
//! is checked against the bytes actually present, so a truncated or lying image is an
//! [`Error`], never a panic.
//!
//! | Bytes | Field |
//! |---|---|
//! | 4 | magic [`IMAGE_MAGIC`] — `SPMI` |
//! | 2 | format version [`IMAGE_VERSION`] |
//! | 2 | flags, reserved, must be zero |
//! | … | the [`ModuleHeader`]: title, format, channel count, speed, tempo, volumes, pan table, flags, dialect, `format_extra`, channel-volume table, `format_data` — each variable-length field length-prefixed |
//! | 16 | counts: samples, patterns, orders, instruments |
//! | … | the sample table ([`SampleIndex`] per entry, name length-prefixed) |
//! | … | the pattern table ([`PatternIndex`] per entry) |
//! | … | the order list, one `u16` each |
//! | … | the instrument table ([`InstrumentDef`] per entry; envelopes length-prefixed, and each 120-entry note map written only when it differs from the default) |
//! | 4 + n | the pattern blob: length in bytes, then the bytes |
//! | 0–3 | zero padding to a 4-byte boundary |
//! | 4 | PCM length, in **frames** |
//! | 2n | the PCM, `i16` little-endian, starting at a 4-byte-aligned offset |
//!
//! # The version rule
//!
//! **Any change to the layout above bumps [`IMAGE_VERSION`].** The reader rejects a
//! version it does not know with [`Error::Unsupported`] rather than reading a field at the
//! wrong offset. There is no forward compatibility and none is wanted: an image is a build
//! product regenerated by `cargo xtask module-images`, not an interchange format, and a
//! stale one in a firmware is a bug that should fail loudly at boot.
//!
//! # Little-endian only, deliberately
//!
//! The point of the format is that the borrowed `i16` slice is the device's PCM, read with
//! no conversion pass. That works because both targets — Xtensa LX6 and RISC-V — are
//! little-endian, as are x86-64, aarch64 and wasm32. On a big-endian host
//! [`Module::from_image`] refuses rather than handing back silently byte-swapped audio;
//! [`Module::from_image_copied`] still works there, because it decodes each frame from
//! explicit little-endian bytes.
//!
//! # Three ways in, named honestly
//!
//! | Constructor | Blob | PCM | Wants |
//! |---|---|---|---|
//! | [`Module::from_image`] | borrowed | borrowed, or `Err` | a 4-byte-aligned `&'static [u8]` |
//! | [`Module::from_image_or_copy`] | borrowed | borrowed when it can be, else copied | any `&'static [u8]` |
//! | [`Module::from_image_copied`] | copied | copied | any `&[u8]`, any alignment, any endianness |
//!
//! Bytes **after** the PCM are ignored rather than rejected, so a firmware may hand a whole
//! flash partition — padded out to its erase-block size — straight to the reader without
//! having to know where the image ends. Everything up to that point is length-checked, and
//! the alignment padding before the PCM must be zero, so nothing can be smuggled through
//! the middle of an image; only past the end of one, where nothing reads it.
//!
//! `include_bytes!` yields a `&'static [u8]` of alignment **1**, so a firmware must place
//! the image behind a `#[repr(C, align(4))]` wrapper (the standard trick) or in an aligned
//! flash partition. [`Module::from_image`] is the constructor that proves it did:
//! misalignment is an `Err`, never a silent copy. [`Module::from_image_or_copy`] is for the
//! caller that would rather spend the RAM than fail to play — a run-time flash partition
//! whose alignment it does not control.

use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec::Vec;
use core::ops::Range;

use starplayer_core::quirks::FormatDialect;
use starplayer_core::{Error, I1F15, SampleId, U0F16};

use crate::header::{ModuleFlags, ModuleFormat, ModuleHeader};
use crate::instrument::{DuplicateAction, DuplicateCheck, Envelope, EnvelopePoint, EnvelopeSpan, InstrumentDef, NOTE_MAP_LENGTH, NewNoteAction, identity_transpose_map};
use crate::module::Module;
use crate::pattern::PatternIndex;
use crate::sample::{AutoVibrato, AutoVibratoWaveform, LoopMode, SampleIndex, SampleSpec, SustainLoop};
use crate::storage::{BlobStorage, PcmStorage};

/// The four bytes every module image starts with.
pub const IMAGE_MAGIC: [u8; 4] = *b"SPMI";

/// The layout version this build writes, and the only one it reads. See the
/// [module documentation](self) for the version rule.
pub const IMAGE_VERSION: u16 = 1;

/// Alignment the PCM region is written at, and the alignment
/// [`Module::from_image`] requires of the whole image in memory.
///
/// `i16` needs only 2, but 4 is what a word-addressed flash mapping wants and what a
/// `#[repr(C, align(4))]` wrapper around `include_bytes!` gives, so the format pins the
/// larger number and the reader checks it.
pub const IMAGE_ALIGNMENT: usize = 4;

const MISALIGNED: Error = Error::Invalid("a module image must be 4-byte aligned in memory to borrow its PCM");
const RESERVED_FLAGS: Error = Error::Invalid("a module image's reserved flags must be zero");
const BAD_ENUM: Error = Error::Invalid("a module image names an enum value this build does not have");
const BAD_BOOL: Error = Error::Invalid("a module image's boolean byte is neither 0 nor 1");
const BAD_TEXT: Error = Error::Invalid("a module image's text is not valid UTF-8");
const BAD_PADDING: Error = Error::Invalid("a module image's alignment padding is not zero");

/// Smallest number of bytes one entry of each table can occupy, used to reject an absurd
/// count **before** anything is allocated for it. The exact sizes do not matter; that they
/// are non-zero and no larger than the real entry does.
const MINIMUM_SAMPLE_BYTES: usize = 36;
const MINIMUM_PATTERN_BYTES: usize = 11;
const MINIMUM_ORDER_BYTES: usize = 2;
const MINIMUM_INSTRUMENT_BYTES: usize = 30;
const MINIMUM_ENVELOPE_POINT_BYTES: usize = 4;

// ── reading ─────────────────────────────────────────────────────────────────────────

impl Module {
    /// Build a module that **borrows** its PCM and its pattern blob from a memory-mapped
    /// image.
    ///
    /// The image is validated to exactly the standard
    /// [`ModuleBuilder::build`](crate::ModuleBuilder::build) applies — the same
    /// `Module::validate` runs over the decoded index tables — because the engine reads a
    /// `Module` from inside `render()`, where an out-of-range offset would be a panic in
    /// the audio callback. Nothing here panics, on any input.
    ///
    /// # Errors
    ///
    /// * [`Error::BadMagic`] — the image does not begin with [`IMAGE_MAGIC`].
    /// * [`Error::Unsupported`] — the image's version is not [`IMAGE_VERSION`], or the host
    ///   is big-endian and the PCM therefore cannot be borrowed.
    /// * [`Error::Invalid`] — the image is not 4-byte aligned in memory, or a field is not
    ///   a value this build has (an enum code, a boolean byte, non-UTF-8 text), or an
    ///   invariant [`ModuleBuilder::build`](crate::ModuleBuilder::build) enforces is
    ///   broken.
    /// * [`Error::Truncated`] — a length field names more bytes than the image holds.
    /// * [`Error::OutOfRange`] — an index table points outside the blob it indexes.
    pub fn from_image(image: &'static [u8]) -> Result<Module, Error> {
        let parts = parse_image(image)?;
        let blob = image.get(parts.blob_bytes.clone()).ok_or(Error::OutOfRange)?;
        let pcm_bytes = image.get(parts.pcm_bytes.clone()).ok_or(Error::OutOfRange)?;
        let pcm = borrow_frames(pcm_bytes)?;
        parts.into_module(BlobStorage::Borrowed(blob), PcmStorage::Borrowed(pcm))
    }

    /// [`Module::from_image`], but an image whose PCM cannot be borrowed — because the
    /// image is not 4-byte aligned, or the host is big-endian — has **only its PCM**
    /// copied onto the heap rather than being refused. The pattern blob is borrowed
    /// either way; it is bytes, so its alignment is never in question.
    ///
    /// Use it where the alignment of the mapping is not yours to choose, such as a module
    /// image written into a flash partition at run time. Where it *is* yours — an image
    /// linked in with `include_bytes!` behind a `#[repr(C, align(4))]` wrapper —
    /// [`Module::from_image`] is the better call, because it fails rather than quietly
    /// spending the RAM the whole exercise was meant to save.
    ///
    /// # Errors
    ///
    /// As [`Module::from_image`], less the alignment and endianness cases it handles.
    pub fn from_image_or_copy(image: &'static [u8]) -> Result<Module, Error> {
        let parts = parse_image(image)?;
        let blob = image.get(parts.blob_bytes.clone()).ok_or(Error::OutOfRange)?;
        let pcm_bytes = image.get(parts.pcm_bytes.clone()).ok_or(Error::OutOfRange)?;
        let pcm = match borrow_frames(pcm_bytes) {
            Ok(borrowed) => PcmStorage::Borrowed(borrowed),
            Err(_) => PcmStorage::Owned(copy_frames(pcm_bytes)),
        };
        parts.into_module(BlobStorage::Borrowed(blob), pcm)
    }

    /// Read an image into an **owned** module, copying both blobs.
    ///
    /// The entry point for bytes that are not `'static` — a file read into a `Vec`, an
    /// image uploaded over the network — and the one that works on a big-endian host,
    /// since it decodes every frame from explicit little-endian bytes. The module it
    /// produces is indistinguishable from the one the loader built: same tables, same
    /// blobs, equal and hashing alike.
    ///
    /// # Errors
    ///
    /// As [`Module::from_image`], less the alignment and endianness cases it cannot hit.
    pub fn from_image_copied(image: &[u8]) -> Result<Module, Error> {
        let parts = parse_image(image)?;
        let blob = image.get(parts.blob_bytes.clone()).ok_or(Error::OutOfRange)?;
        let pcm_bytes = image.get(parts.pcm_bytes.clone()).ok_or(Error::OutOfRange)?;
        let blob = BlobStorage::Owned(Box::from(blob));
        parts.into_module(blob, PcmStorage::Owned(copy_frames(pcm_bytes)))
    }
}

/// Everything an image holds except the two blobs, which stay as byte ranges into the
/// image so that each constructor above can decide how to hold them.
struct ImageParts {
    header: ModuleHeader,
    samples: Box<[SampleIndex]>,
    patterns: Box<[PatternIndex]>,
    orders: Box<[u16]>,
    instruments: Box<[InstrumentDef]>,
    blob_bytes: Range<usize>,
    pcm_bytes: Range<usize>,
}

impl ImageParts {
    /// Assemble the module and run the model's own invariant check over it — the same one
    /// [`ModuleBuilder::build`](crate::ModuleBuilder::build) runs, so a module that came
    /// out of an image has passed exactly what a loaded module passed.
    fn into_module(self, blob: BlobStorage, pcm: PcmStorage) -> Result<Module, Error> {
        let module = Module::from_parts(blob, pcm, self.samples, self.patterns, self.orders, self.instruments, self.header);
        module.validate()?;
        Ok(module)
    }
}

/// Borrow the PCM region as `i16` frames, or say why it cannot be borrowed.
#[cfg(target_endian = "little")]
fn borrow_frames(bytes: &'static [u8]) -> Result<&'static [i16], Error> {
    if !(bytes.as_ptr() as usize).is_multiple_of(IMAGE_ALIGNMENT) {
        return Err(MISALIGNED);
    }
    // The cast can still refuse — it checks `align_of::<i16>()` and the length itself —
    // and a refusal is reported rather than worked around, because a silent copy here is
    // precisely the RAM cost this format exists to avoid.
    bytemuck::try_cast_slice(bytes).map_err(|_| MISALIGNED)
}

/// On a big-endian host the borrowed frames would be byte-swapped audio, so there is no
/// borrow to hand back. See the [module documentation](self).
#[cfg(target_endian = "big")]
fn borrow_frames(_bytes: &'static [u8]) -> Result<&'static [i16], Error> {
    Err(Error::Unsupported("a module image's PCM can only be borrowed on a little-endian host"))
}

/// Decode the PCM region into owned frames, from explicit little-endian bytes so the
/// result is the same on every host.
fn copy_frames(bytes: &[u8]) -> Box<[i16]> {
    let frames: Vec<i16> = bytes
        .chunks_exact(2)
        // `chunks_exact(2)` only ever yields two bytes, so the `Err` arm is unreachable;
        // it is written as a fallback rather than an `unwrap` because this crate forbids
        // both panicking and indexing.
        .map(|pair| match <[u8; 2]>::try_from(pair) {
            Ok(pair) => i16::from_le_bytes(pair),
            Err(_) => 0,
        })
        .collect();
    frames.into_boxed_slice()
}

/// A bounds-checked forward cursor over the image. Every read either advances or returns
/// [`Error::Truncated`] naming where it ran out.
struct Cursor<'image> {
    bytes: &'image [u8],
    offset: usize,
}

impl<'image> Cursor<'image> {
    fn new(bytes: &'image [u8]) -> Cursor<'image> { Cursor { bytes, offset: 0 } }

    fn remaining(&self) -> usize { self.bytes.len().saturating_sub(self.offset) }

    fn take(&mut self, length: usize) -> Result<&'image [u8], Error> {
        let truncated = Error::Truncated { offset: self.offset, needed: length };
        let end = self.offset.checked_add(length).ok_or(truncated)?;
        let slice = self.bytes.get(self.offset..end).ok_or(truncated)?;
        self.offset = end;
        Ok(slice)
    }

    /// The byte range `length` bytes from here occupies, skipping over it. The range is
    /// how a blob reaches its storage without being copied first.
    fn take_range(&mut self, length: usize) -> Result<Range<usize>, Error> {
        let start = self.offset;
        self.take(length)?;
        Ok(start..self.offset)
    }

    fn u8(&mut self) -> Result<u8, Error> {
        let bytes = self.take(1)?;
        bytes.first().copied().ok_or(Error::Truncated { offset: self.offset, needed: 1 })
    }

    fn i8(&mut self) -> Result<i8, Error> { Ok(self.u8()? as i8) }

    fn u16(&mut self) -> Result<u16, Error> {
        let bytes = <[u8; 2]>::try_from(self.take(2)?).map_err(|_| Error::Truncated { offset: self.offset, needed: 2 })?;
        Ok(u16::from_le_bytes(bytes))
    }

    fn i16(&mut self) -> Result<i16, Error> { Ok(self.u16()? as i16) }

    fn u32(&mut self) -> Result<u32, Error> {
        let bytes = <[u8; 4]>::try_from(self.take(4)?).map_err(|_| Error::Truncated { offset: self.offset, needed: 4 })?;
        Ok(u32::from_le_bytes(bytes))
    }

    fn boolean(&mut self) -> Result<bool, Error> {
        match self.u8()? {
            0 => Ok(false),
            1 => Ok(true),
            _ => Err(BAD_BOOL),
        }
    }

    /// A `u32` length followed by that many bytes of UTF-8.
    fn text(&mut self) -> Result<Box<str>, Error> {
        let length = self.length()?;
        let bytes = self.take(length)?;
        let text = core::str::from_utf8(bytes).map_err(|_| BAD_TEXT)?;
        Ok(String::from(text).into_boxed_str())
    }

    /// A `u32` byte length, as a `usize`.
    fn length(&mut self) -> Result<usize, Error> { Ok(self.u32()? as usize) }

    /// A `u32` entry count, refused **before** anything is allocated for it if the image
    /// is too short to hold that many entries of `minimum_entry_bytes`.
    ///
    /// Without this a four-byte count of `0xFFFF_FFFF` would ask for gigabytes from a
    /// forty-byte input, which is the shape of every fuzzer-found allocation blowup.
    fn count(&mut self, minimum_entry_bytes: usize) -> Result<usize, Error> {
        let count = self.u32()? as usize;
        let needed = count.checked_mul(minimum_entry_bytes).ok_or(Error::Truncated { offset: self.offset, needed: usize::MAX })?;
        if needed > self.remaining() {
            return Err(Error::Truncated { offset: self.offset, needed });
        }
        Ok(count)
    }

    /// Skip zero padding up to the next [`IMAGE_ALIGNMENT`] boundary. The padding must be
    /// zero, so an image cannot smuggle anything through it.
    fn align(&mut self) -> Result<(), Error> {
        let padding = (IMAGE_ALIGNMENT - self.offset % IMAGE_ALIGNMENT) % IMAGE_ALIGNMENT;
        if self.take(padding)?.iter().any(|byte| *byte != 0) {
            return Err(BAD_PADDING);
        }
        Ok(())
    }
}

fn parse_image(image: &[u8]) -> Result<ImageParts, Error> {
    let mut cursor = Cursor::new(image);
    if cursor.take(IMAGE_MAGIC.len())? != IMAGE_MAGIC {
        return Err(Error::BadMagic);
    }
    if cursor.u16()? != IMAGE_VERSION {
        return Err(Error::Unsupported("a module image of a layout version this build does not read"));
    }
    if cursor.u16()? != 0 {
        return Err(RESERVED_FLAGS);
    }

    let header = read_header(&mut cursor)?;
    let sample_count = cursor.count(MINIMUM_SAMPLE_BYTES)?;
    let pattern_count = cursor.count(MINIMUM_PATTERN_BYTES)?;
    let order_count = cursor.count(MINIMUM_ORDER_BYTES)?;
    let instrument_count = cursor.count(MINIMUM_INSTRUMENT_BYTES)?;

    let mut samples = Vec::with_capacity(sample_count);
    for _ in 0..sample_count {
        samples.push(read_sample(&mut cursor)?);
    }
    let mut patterns = Vec::with_capacity(pattern_count);
    for _ in 0..pattern_count {
        patterns.push(read_pattern(&mut cursor)?);
    }
    let mut orders = Vec::with_capacity(order_count);
    for _ in 0..order_count {
        orders.push(cursor.u16()?);
    }
    let mut instruments = Vec::with_capacity(instrument_count);
    for _ in 0..instrument_count {
        instruments.push(read_instrument(&mut cursor)?);
    }

    let blob_length = cursor.length()?;
    let blob_bytes = cursor.take_range(blob_length)?;
    cursor.align()?;
    let pcm_frames = cursor.length()?;
    let pcm_length = pcm_frames.checked_mul(2).ok_or(Error::TooLarge("a module image's PCM length"))?;
    let pcm_bytes = cursor.take_range(pcm_length)?;

    Ok(ImageParts {
        header,
        samples: samples.into_boxed_slice(),
        patterns: patterns.into_boxed_slice(),
        orders: orders.into_boxed_slice(),
        instruments: instruments.into_boxed_slice(),
        blob_bytes,
        pcm_bytes,
    })
}

fn read_header(cursor: &mut Cursor<'_>) -> Result<ModuleHeader, Error> {
    let title = cursor.text()?;
    let format = module_format_from_code(cursor.u8()?)?;
    let channel_count = cursor.u8()?;
    let initial_speed = cursor.u8()?;
    let flags = read_module_flags(cursor.u8()?)?;
    let initial_tempo = cursor.u16()?;
    let global_volume = U0F16::from_bits(cursor.u16()?);
    let master_volume = U0F16::from_bits(cursor.u16()?);
    let dialect = dialect_from_code(cursor.u16()?)?;
    let format_extra = cursor.u32()?;

    let pan_count = cursor.count(2)?;
    let mut default_pan = Vec::with_capacity(pan_count);
    for _ in 0..pan_count {
        default_pan.push(I1F15::from_bits(cursor.i16()?));
    }
    let channel_volume_count = cursor.count(2)?;
    let mut default_channel_volume = Vec::with_capacity(channel_volume_count);
    for _ in 0..channel_volume_count {
        default_channel_volume.push(U0F16::from_bits(cursor.u16()?));
    }
    let format_data_length = cursor.length()?;
    let format_data = Box::from(cursor.take(format_data_length)?);

    Ok(ModuleHeader {
        title,
        format,
        channel_count,
        initial_speed,
        initial_tempo,
        global_volume,
        master_volume,
        default_pan: default_pan.into_boxed_slice(),
        flags,
        dialect,
        format_extra,
        default_channel_volume: default_channel_volume.into_boxed_slice(),
        format_data,
    })
}

fn read_sample(cursor: &mut Cursor<'_>) -> Result<SampleIndex, Error> {
    let pcm_offset = cursor.u32()?;
    let length_frames = cursor.u32()?;
    let specification = SampleSpec {
        loop_mode: loop_mode_from_code(cursor.u8()?)?,
        loop_start: cursor.u32()?,
        loop_end: cursor.u32()?,
        default_volume: U0F16::from_bits(cursor.u16()?),
        reference_rate_hz: cursor.u32()?,
        relative_note: cursor.i8()?,
        finetune: cursor.i8()?,
        default_pan: read_optional_pan(cursor)?,
        auto_vibrato: AutoVibrato {
            waveform: auto_vibrato_waveform_from_code(cursor.u8()?)?,
            sweep: cursor.u8()?,
            depth: cursor.u8()?,
            rate: cursor.u8()?,
        },
        sustain_loop: read_optional_sustain_loop(cursor)?,
        rate_scale_log2: cursor.u8()?,
        name: String::from(cursor.text()?),
    };
    Ok(SampleIndex::new(pcm_offset, length_frames, specification))
}

fn read_pattern(cursor: &mut Cursor<'_>) -> Result<PatternIndex, Error> {
    let blob_offset = cursor.u32()?;
    let length_bytes = cursor.u32()?;
    let rows = cursor.u16()?;
    let channels = cursor.u8()?;
    Ok(PatternIndex::new(blob_offset, length_bytes, rows, channels))
}

fn read_instrument(cursor: &mut Cursor<'_>) -> Result<InstrumentDef, Error> {
    let name = cursor.text()?;
    // The id is written whether or not the instrument has one, so it is read either way
    // too: an `Option` costs a fixed three bytes here, never a variable-length field.
    let present = cursor.boolean()?;
    let sample = present.then_some(SampleId(cursor.u16()?));
    let default_volume = U0F16::from_bits(cursor.u16()?);

    let mut note_sample_map = [0u16; NOTE_MAP_LENGTH];
    if cursor.boolean()? {
        for entry in note_sample_map.iter_mut() {
            *entry = cursor.u16()?;
        }
    }
    let mut note_transpose_map = identity_transpose_map();
    if cursor.boolean()? {
        for entry in note_transpose_map.iter_mut() {
            *entry = cursor.u8()?;
        }
    }

    let volume_envelope = read_optional_envelope(cursor)?;
    let panning_envelope = read_optional_envelope(cursor)?;
    let pitch_envelope = read_optional_envelope(cursor)?;
    let fadeout = cursor.u16()?;
    let new_note_action = new_note_action_from_code(cursor.u8()?)?;
    let duplicate_check = duplicate_check_from_code(cursor.u8()?)?;
    let duplicate_action = duplicate_action_from_code(cursor.u8()?)?;
    let global_volume = U0F16::from_bits(cursor.u16()?);
    let default_pan = read_optional_pan(cursor)?;
    let pitch_pan_separation = cursor.i8()?;
    let pitch_pan_centre = cursor.u8()?;
    let random_volume_variation = cursor.u8()?;
    let random_pan_variation = cursor.u8()?;
    let initial_filter_cutoff = read_optional_byte(cursor)?;
    let initial_filter_resonance = read_optional_byte(cursor)?;
    let pitch_envelope_is_filter = cursor.boolean()?;

    Ok(InstrumentDef {
        name,
        sample,
        default_volume,
        note_sample_map,
        note_transpose_map,
        volume_envelope,
        panning_envelope,
        pitch_envelope,
        fadeout,
        new_note_action,
        duplicate_check,
        duplicate_action,
        global_volume,
        default_pan,
        pitch_pan_separation,
        pitch_pan_centre,
        random_volume_variation,
        random_pan_variation,
        initial_filter_cutoff,
        initial_filter_resonance,
        pitch_envelope_is_filter,
    })
}

fn read_optional_envelope(cursor: &mut Cursor<'_>) -> Result<Option<Envelope>, Error> {
    if !cursor.boolean()? {
        return Ok(None);
    }
    let point_count = cursor.count(MINIMUM_ENVELOPE_POINT_BYTES)?;
    let mut points = Vec::with_capacity(point_count);
    for _ in 0..point_count {
        points.push(EnvelopePoint { tick: cursor.u16()?, value: cursor.i16()? });
    }
    let sustain = read_optional_span(cursor)?;
    let loop_span = read_optional_span(cursor)?;
    let carry = cursor.boolean()?;
    Ok(Some(Envelope { points: points.into_boxed_slice(), sustain, loop_span, carry }))
}

fn read_optional_span(cursor: &mut Cursor<'_>) -> Result<Option<EnvelopeSpan>, Error> {
    let present = cursor.boolean()?;
    let span = EnvelopeSpan { start: cursor.u8()?, end: cursor.u8()? };
    Ok(present.then_some(span))
}

fn read_optional_pan(cursor: &mut Cursor<'_>) -> Result<Option<I1F15>, Error> {
    let present = cursor.boolean()?;
    let pan = I1F15::from_bits(cursor.i16()?);
    Ok(present.then_some(pan))
}

fn read_optional_byte(cursor: &mut Cursor<'_>) -> Result<Option<u8>, Error> {
    let present = cursor.boolean()?;
    let value = cursor.u8()?;
    Ok(present.then_some(value))
}

fn read_optional_sustain_loop(cursor: &mut Cursor<'_>) -> Result<Option<SustainLoop>, Error> {
    let present = cursor.boolean()?;
    let sustain = SustainLoop { mode: loop_mode_from_code(cursor.u8()?)?, start: cursor.u32()?, end: cursor.u32()? };
    Ok(present.then_some(sustain))
}

fn read_module_flags(bits: u8) -> Result<ModuleFlags, Error> {
    const KNOWN: u8 = 0b0000_1111;
    if bits & !KNOWN != 0 {
        return Err(RESERVED_FLAGS);
    }
    Ok(ModuleFlags {
        amiga_limits: bits & 0b0001 != 0,
        linear_slides: bits & 0b0010 != 0,
        fast_volume_slides: bits & 0b0100 != 0,
        stereo: bits & 0b1000 != 0,
    })
}

// ── writing ─────────────────────────────────────────────────────────────────────────

impl Module {
    /// Serialise this module as a module image — the inverse of [`Module::from_image`].
    ///
    /// Host-side only in practice (`cargo xtask module-image` is its one caller), but not
    /// feature-gated: it is a plain function over `alloc`, so a firmware that never calls
    /// it never links it, and a feature would have cost every test and every tool a flag
    /// for nothing.
    ///
    /// Every length is written as a `u32` and a length that would not fit saturates, which
    /// the reader then rejects as [`Error::Truncated`] — so a module too large for the
    /// format produces an image that fails to load rather than one that loads wrongly. No
    /// module any loader in this workspace can produce is anywhere near that: the model's
    /// own offsets are `u32` already.
    pub fn to_image(&self) -> Vec<u8> {
        let mut image = Vec::new();
        image.extend_from_slice(&IMAGE_MAGIC);
        push_u16(&mut image, IMAGE_VERSION);
        push_u16(&mut image, 0);

        write_header(&mut image, self.header());
        push_length(&mut image, self.samples().len());
        push_length(&mut image, self.patterns().len());
        push_length(&mut image, self.orders().len());
        push_length(&mut image, self.instruments().len());

        for sample in self.samples().iter() {
            write_sample(&mut image, sample);
        }
        for pattern in self.patterns().iter() {
            write_pattern(&mut image, pattern);
        }
        for order in self.orders().iter() {
            push_u16(&mut image, *order);
        }
        for instrument in self.instruments().iter() {
            write_instrument(&mut image, instrument);
        }

        push_length(&mut image, self.blob().len());
        image.extend_from_slice(self.blob());
        // The PCM's own length field is four bytes, so aligning *before* it is what lands
        // the frames themselves on a 4-byte boundary.
        while !image.len().is_multiple_of(IMAGE_ALIGNMENT) {
            image.push(0);
        }
        push_length(&mut image, self.pcm().len());
        for frame in self.pcm().iter() {
            image.extend_from_slice(&frame.to_le_bytes());
        }
        image
    }

    /// How many bytes of `to_image`'s output are sample frames — the number that decides
    /// whether a module fits a flash partition, and the one an `i8` storage would halve
    /// (M8-I2 research point 2).
    pub fn image_pcm_bytes(&self) -> usize { self.pcm().len().saturating_mul(2) }
}

fn write_header(image: &mut Vec<u8>, header: &ModuleHeader) {
    push_text(image, &header.title);
    image.push(module_format_code(header.format));
    image.push(header.channel_count);
    image.push(header.initial_speed);
    image.push(module_flags_bits(header.flags));
    push_u16(image, header.initial_tempo);
    push_u16(image, header.global_volume.to_bits());
    push_u16(image, header.master_volume.to_bits());
    push_u16(image, dialect_code(header.dialect));
    push_u32(image, header.format_extra);

    push_length(image, header.default_pan.len());
    for pan in header.default_pan.iter() {
        push_u16(image, pan.to_bits() as u16);
    }
    push_length(image, header.default_channel_volume.len());
    for volume in header.default_channel_volume.iter() {
        push_u16(image, volume.to_bits());
    }
    push_length(image, header.format_data.len());
    image.extend_from_slice(&header.format_data);
}

fn write_sample(image: &mut Vec<u8>, sample: &SampleIndex) {
    let specification = sample.to_spec();
    push_u32(image, sample.pcm_offset());
    push_u32(image, sample.length_frames());
    image.push(loop_mode_code(specification.loop_mode));
    push_u32(image, specification.loop_start);
    push_u32(image, specification.loop_end);
    push_u16(image, specification.default_volume.to_bits());
    push_u32(image, specification.reference_rate_hz);
    image.push(specification.relative_note as u8);
    image.push(specification.finetune as u8);
    write_optional_pan(image, specification.default_pan);
    image.push(auto_vibrato_waveform_code(specification.auto_vibrato.waveform));
    image.push(specification.auto_vibrato.sweep);
    image.push(specification.auto_vibrato.depth);
    image.push(specification.auto_vibrato.rate);
    write_optional_sustain_loop(image, specification.sustain_loop);
    image.push(specification.rate_scale_log2);
    push_text(image, &specification.name);
}

fn write_pattern(image: &mut Vec<u8>, pattern: &PatternIndex) {
    push_u32(image, pattern.blob_offset());
    push_u32(image, pattern.length_bytes());
    push_u16(image, pattern.rows());
    image.push(pattern.channels());
}

fn write_instrument(image: &mut Vec<u8>, instrument: &InstrumentDef) {
    push_text(image, &instrument.name);
    match instrument.sample {
        Some(SampleId(sample)) => {
            image.push(1);
            push_u16(image, sample);
        }
        None => {
            image.push(0);
            push_u16(image, 0);
        }
    }
    push_u16(image, instrument.default_volume.to_bits());
    // The two 120-entry note maps are written only when they are not the default an
    // MOD/S3M/MTM instrument always carries — all-zero, and the identity transpose. That
    // is 360 bytes saved per instrument, which on a 31-instrument MOD is most of the
    // image; see `Module::to_image`.
    let note_sample_map_is_default = instrument.note_sample_map.iter().all(|entry| *entry == 0);
    image.push(u8::from(!note_sample_map_is_default));
    if !note_sample_map_is_default {
        for entry in instrument.note_sample_map.iter() {
            push_u16(image, *entry);
        }
    }
    let note_transpose_map_is_default = instrument.note_transpose_map == identity_transpose_map();
    image.push(u8::from(!note_transpose_map_is_default));
    if !note_transpose_map_is_default {
        image.extend_from_slice(&instrument.note_transpose_map);
    }

    write_optional_envelope(image, instrument.volume_envelope.as_ref());
    write_optional_envelope(image, instrument.panning_envelope.as_ref());
    write_optional_envelope(image, instrument.pitch_envelope.as_ref());
    push_u16(image, instrument.fadeout);
    image.push(new_note_action_code(instrument.new_note_action));
    image.push(duplicate_check_code(instrument.duplicate_check));
    image.push(duplicate_action_code(instrument.duplicate_action));
    push_u16(image, instrument.global_volume.to_bits());
    write_optional_pan(image, instrument.default_pan);
    image.push(instrument.pitch_pan_separation as u8);
    image.push(instrument.pitch_pan_centre);
    image.push(instrument.random_volume_variation);
    image.push(instrument.random_pan_variation);
    write_optional_byte(image, instrument.initial_filter_cutoff);
    write_optional_byte(image, instrument.initial_filter_resonance);
    image.push(u8::from(instrument.pitch_envelope_is_filter));
}

fn write_optional_envelope(image: &mut Vec<u8>, envelope: Option<&Envelope>) {
    let Some(envelope) = envelope else {
        image.push(0);
        return;
    };
    image.push(1);
    push_length(image, envelope.points.len());
    for point in envelope.points.iter() {
        push_u16(image, point.tick);
        push_u16(image, point.value as u16);
    }
    write_optional_span(image, envelope.sustain);
    write_optional_span(image, envelope.loop_span);
    image.push(u8::from(envelope.carry));
}

fn write_optional_span(image: &mut Vec<u8>, span: Option<EnvelopeSpan>) {
    image.push(u8::from(span.is_some()));
    let span = span.unwrap_or_default();
    image.push(span.start);
    image.push(span.end);
}

fn write_optional_pan(image: &mut Vec<u8>, pan: Option<I1F15>) {
    image.push(u8::from(pan.is_some()));
    push_u16(image, pan.unwrap_or(I1F15::ZERO).to_bits() as u16);
}

fn write_optional_byte(image: &mut Vec<u8>, value: Option<u8>) {
    image.push(u8::from(value.is_some()));
    image.push(value.unwrap_or(0));
}

fn write_optional_sustain_loop(image: &mut Vec<u8>, sustain: Option<SustainLoop>) {
    image.push(u8::from(sustain.is_some()));
    let sustain = sustain.unwrap_or(SustainLoop { mode: LoopMode::None, start: 0, end: 0 });
    image.push(loop_mode_code(sustain.mode));
    push_u32(image, sustain.start);
    push_u32(image, sustain.end);
}

fn push_u16(image: &mut Vec<u8>, value: u16) { image.extend_from_slice(&value.to_le_bytes()); }

fn push_u32(image: &mut Vec<u8>, value: u32) { image.extend_from_slice(&value.to_le_bytes()); }

/// A length or a count, as a `u32`. See [`Module::to_image`] for what saturation means.
fn push_length(image: &mut Vec<u8>, value: usize) { push_u32(image, u32::try_from(value).unwrap_or(u32::MAX)); }

fn push_text(image: &mut Vec<u8>, text: &str) {
    push_length(image, text.len());
    image.extend_from_slice(text.as_bytes());
}

fn module_flags_bits(flags: ModuleFlags) -> u8 {
    u8::from(flags.amiga_limits) | u8::from(flags.linear_slides) << 1 | u8::from(flags.fast_volume_slides) << 2 | u8::from(flags.stereo) << 3
}

// ── enum codes ──────────────────────────────────────────────────────────────────────
//
// Written out rather than derived from the discriminants, so that reordering a variant in
// the model cannot silently change what an image means. Each `..._code` match is
// exhaustive, so a new variant is a compile error here — which is where the version bump
// gets decided.

const fn module_format_code(format: ModuleFormat) -> u8 {
    match format {
        ModuleFormat::S3m => 0,
        ModuleFormat::Mod => 1,
        ModuleFormat::Mtm => 2,
        ModuleFormat::Xm => 3,
        ModuleFormat::It => 4,
    }
}

fn module_format_from_code(code: u8) -> Result<ModuleFormat, Error> {
    match code {
        0 => Ok(ModuleFormat::S3m),
        1 => Ok(ModuleFormat::Mod),
        2 => Ok(ModuleFormat::Mtm),
        3 => Ok(ModuleFormat::Xm),
        4 => Ok(ModuleFormat::It),
        _ => Err(BAD_ENUM),
    }
}

const fn loop_mode_code(mode: LoopMode) -> u8 {
    match mode {
        LoopMode::None => 0,
        LoopMode::Forward => 1,
        LoopMode::PingPong => 2,
    }
}

fn loop_mode_from_code(code: u8) -> Result<LoopMode, Error> {
    match code {
        0 => Ok(LoopMode::None),
        1 => Ok(LoopMode::Forward),
        2 => Ok(LoopMode::PingPong),
        _ => Err(BAD_ENUM),
    }
}

const fn auto_vibrato_waveform_code(waveform: AutoVibratoWaveform) -> u8 {
    match waveform {
        AutoVibratoWaveform::Sine => 0,
        AutoVibratoWaveform::RampDown => 1,
        AutoVibratoWaveform::Square => 2,
        AutoVibratoWaveform::Random => 3,
        AutoVibratoWaveform::RampUp => 4,
    }
}

fn auto_vibrato_waveform_from_code(code: u8) -> Result<AutoVibratoWaveform, Error> {
    match code {
        0 => Ok(AutoVibratoWaveform::Sine),
        1 => Ok(AutoVibratoWaveform::RampDown),
        2 => Ok(AutoVibratoWaveform::Square),
        3 => Ok(AutoVibratoWaveform::Random),
        4 => Ok(AutoVibratoWaveform::RampUp),
        _ => Err(BAD_ENUM),
    }
}

const fn new_note_action_code(action: NewNoteAction) -> u8 {
    match action {
        NewNoteAction::Cut => 0,
        NewNoteAction::Continue => 1,
        NewNoteAction::NoteOff => 2,
        NewNoteAction::NoteFade => 3,
    }
}

fn new_note_action_from_code(code: u8) -> Result<NewNoteAction, Error> {
    match code {
        0 => Ok(NewNoteAction::Cut),
        1 => Ok(NewNoteAction::Continue),
        2 => Ok(NewNoteAction::NoteOff),
        3 => Ok(NewNoteAction::NoteFade),
        _ => Err(BAD_ENUM),
    }
}

const fn duplicate_check_code(check: DuplicateCheck) -> u8 {
    match check {
        DuplicateCheck::Off => 0,
        DuplicateCheck::Note => 1,
        DuplicateCheck::Sample => 2,
        DuplicateCheck::Instrument => 3,
    }
}

fn duplicate_check_from_code(code: u8) -> Result<DuplicateCheck, Error> {
    match code {
        0 => Ok(DuplicateCheck::Off),
        1 => Ok(DuplicateCheck::Note),
        2 => Ok(DuplicateCheck::Sample),
        3 => Ok(DuplicateCheck::Instrument),
        _ => Err(BAD_ENUM),
    }
}

const fn duplicate_action_code(action: DuplicateAction) -> u8 {
    match action {
        DuplicateAction::Cut => 0,
        DuplicateAction::NoteOff => 1,
        DuplicateAction::NoteFade => 2,
    }
}

fn duplicate_action_from_code(code: u8) -> Result<DuplicateAction, Error> {
    match code {
        0 => Ok(DuplicateAction::Cut),
        1 => Ok(DuplicateAction::NoteOff),
        2 => Ok(DuplicateAction::NoteFade),
        _ => Err(BAD_ENUM),
    }
}

const fn dialect_code(dialect: FormatDialect) -> u16 {
    match dialect {
        FormatDialect::Unknown => 0,
        FormatDialect::ProTracker => 1,
        FormatDialect::Noisetracker => 2,
        FormatDialect::ProTracker3 => 3,
        FormatDialect::Octalyser => 4,
        FormatDialect::DigitalTracker => 5,
        FormatDialect::Startrekker => 6,
        FormatDialect::FastTracker => 7,
        FormatDialect::MultiTracker => 8,
        FormatDialect::ScreamTracker321 => 9,
        FormatDialect::ScreamTracker301 => 10,
        FormatDialect::ModPlug116 => 11,
        FormatDialect::ImagoOrpheus => 12,
        FormatDialect::FastTracker2 => 13,
        FormatDialect::MilkyTracker => 14,
        FormatDialect::ModPlugXm => 15,
        FormatDialect::OpenMptXm => 16,
        FormatDialect::SkaleTracker => 17,
        FormatDialect::UnknownXm => 18,
        FormatDialect::ImpulseTracker => 19,
        FormatDialect::ImpulseTracker200 => 20,
        FormatDialect::ImpulseTracker104 => 21,
        FormatDialect::ImpulseTracker100 => 22,
        FormatDialect::OpenMptIt => 23,
        FormatDialect::SchismTracker => 24,
        FormatDialect::ModPlugIt => 25,
    }
}

fn dialect_from_code(code: u16) -> Result<FormatDialect, Error> {
    match code {
        0 => Ok(FormatDialect::Unknown),
        1 => Ok(FormatDialect::ProTracker),
        2 => Ok(FormatDialect::Noisetracker),
        3 => Ok(FormatDialect::ProTracker3),
        4 => Ok(FormatDialect::Octalyser),
        5 => Ok(FormatDialect::DigitalTracker),
        6 => Ok(FormatDialect::Startrekker),
        7 => Ok(FormatDialect::FastTracker),
        8 => Ok(FormatDialect::MultiTracker),
        9 => Ok(FormatDialect::ScreamTracker321),
        10 => Ok(FormatDialect::ScreamTracker301),
        11 => Ok(FormatDialect::ModPlug116),
        12 => Ok(FormatDialect::ImagoOrpheus),
        13 => Ok(FormatDialect::FastTracker2),
        14 => Ok(FormatDialect::MilkyTracker),
        15 => Ok(FormatDialect::ModPlugXm),
        16 => Ok(FormatDialect::OpenMptXm),
        17 => Ok(FormatDialect::SkaleTracker),
        18 => Ok(FormatDialect::UnknownXm),
        19 => Ok(FormatDialect::ImpulseTracker),
        20 => Ok(FormatDialect::ImpulseTracker200),
        21 => Ok(FormatDialect::ImpulseTracker104),
        22 => Ok(FormatDialect::ImpulseTracker100),
        23 => Ok(FormatDialect::OpenMptIt),
        24 => Ok(FormatDialect::SchismTracker),
        25 => Ok(FormatDialect::ModPlugIt),
        _ => Err(BAD_ENUM),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::builder::ModuleBuilder;
    use crate::enhance::{EnhancedPcm, SampleEnhancer, SamplePcm};
    use crate::module::{ORDER_END, ORDER_MARKER};
    use alloc::vec;

    /// Leak `bytes` as a `'static` slice whose first byte is 4-byte aligned, which is what
    /// a firmware's `#[repr(C, align(4))]` wrapper around `include_bytes!` produces.
    ///
    /// Allocating as `u32` is the whole trick: `Box<[u8]>` promises alignment 1 only, so a
    /// test that leaked one would pass or fail on the allocator's mood.
    fn leak_aligned(bytes: &[u8]) -> &'static [u8] {
        let words: Vec<u32> = vec![0; bytes.len().div_ceil(4)];
        let leaked: &'static mut [u8] = bytemuck::cast_slice_mut(Vec::leak(words));
        let Some(head) = leaked.get_mut(..bytes.len()) else { return &[] };
        head.copy_from_slice(bytes);
        head
    }

    /// The same bytes one byte later in memory, so the PCM cannot be 4-byte aligned.
    fn leak_misaligned(bytes: &[u8]) -> &'static [u8] {
        let mut shifted = vec![0u8];
        shifted.extend_from_slice(bytes);
        leak_aligned(&shifted).get(1..).unwrap_or(&[])
    }

    /// A module that exercises every optional field the image carries: a forward loop, a
    /// ping-pong loop, a sustain loop, a sample pan, auto-vibrato, both marker orders, an
    /// instrument with envelopes and IT's whole tail of settings.
    fn exhaustive_module() -> Module {
        let mut builder = ModuleBuilder::new();
        let looping = builder
            .add_sample(&[0, 1, 2, 3, 4, 5, 6, 7], SampleSpec::one_shot("loop").with_forward_loop(2, 6))
            .expect("a valid looping sample");
        let ping_pong = builder
            .add_sample(
                &[10, 20, 30, 40],
                SampleSpec { loop_mode: LoopMode::PingPong, loop_start: 0, loop_end: 4, ..SampleSpec::one_shot("pingpong") },
            )
            .expect("a valid ping-pong sample");
        let sustaining = builder
            .add_sample(
                &[1, 2, 3, 4, 5, 6],
                SampleSpec {
                    sustain_loop: Some(SustainLoop { mode: LoopMode::Forward, start: 1, end: 4 }),
                    default_pan: Some(I1F15::from_bits(-12345)),
                    auto_vibrato: AutoVibrato { waveform: AutoVibratoWaveform::RampUp, sweep: 3, depth: 9, rate: 42 },
                    relative_note: -7,
                    finetune: 60,
                    ..SampleSpec::one_shot("sustain").with_reference_rate(22050)
                },
            )
            .expect("a valid sustaining sample");

        let envelope = Envelope {
            points: vec![EnvelopePoint { tick: 0, value: 0 }, EnvelopePoint { tick: 40, value: -32 }].into_boxed_slice(),
            sustain: Some(EnvelopeSpan { start: 0, end: 1 }),
            loop_span: None,
            carry: true,
        };
        let mut instrument = InstrumentDef::from_sample("lead", looping, U0F16::from_bits(40000));
        instrument.note_sample_map = core::array::from_fn(|note| (note % 3) as u16);
        instrument.note_transpose_map = core::array::from_fn(|note| (note as u8).wrapping_add(1));
        instrument.volume_envelope = Some(envelope.clone());
        instrument.panning_envelope = Some(Envelope { loop_span: Some(EnvelopeSpan { start: 1, end: 1 }), ..envelope });
        instrument.fadeout = 512;
        instrument.new_note_action = NewNoteAction::NoteFade;
        instrument.duplicate_check = DuplicateCheck::Instrument;
        instrument.duplicate_action = DuplicateAction::NoteOff;
        instrument.default_pan = Some(I1F15::from_bits(4096));
        instrument.pitch_pan_separation = -4;
        instrument.pitch_pan_centre = 60;
        instrument.random_volume_variation = 25;
        instrument.random_pan_variation = 7;
        instrument.initial_filter_cutoff = Some(64);
        instrument.initial_filter_resonance = None;
        instrument.pitch_envelope_is_filter = true;
        builder.add_instrument(instrument).expect("an instrument");
        builder.add_instrument(InstrumentDef { name: String::from("empty").into_boxed_str(), sample: None, ..InstrumentDef::default() }).expect("an instrument");
        builder.add_instrument(InstrumentDef::from_sample("pp", ping_pong, U0F16::MAX)).expect("an instrument");
        builder.add_instrument(InstrumentDef::from_sample("sus", sustaining, U0F16::MAX)).expect("an instrument");

        builder.add_pattern(&[1, 2, 3, 4, 5], 64, 4).expect("a valid pattern");
        builder.add_pattern(&[9], 16, 2).expect("a valid pattern");
        builder.set_orders(&[0, ORDER_MARKER, 1, ORDER_END]);

        let mut header = ModuleHeader::new(ModuleFormat::It, 4);
        header.title = String::from("every field").into_boxed_str();
        header.initial_speed = 3;
        header.initial_tempo = 150;
        header.global_volume = U0F16::from_bits(30000);
        header.master_volume = U0F16::from_bits(12345);
        header.default_pan = vec![I1F15::from_bits(-32768), I1F15::ZERO, I1F15::MAX, I1F15::from_bits(99)].into_boxed_slice();
        header.default_channel_volume = vec![U0F16::MAX, U0F16::from_bits(1), U0F16::from_bits(2), U0F16::from_bits(3)].into_boxed_slice();
        header.flags = ModuleFlags { amiga_limits: true, linear_slides: false, fast_volume_slides: true, stereo: true };
        header.dialect = FormatDialect::ImpulseTracker200;
        header.format_extra = 0xDEAD_BEEF;
        header.format_data = vec![7u8, 8, 9].into_boxed_slice();
        builder.set_header(header);
        builder.build().expect("a valid module")
    }

    /// An enhancer that changes nothing, for the rebuild-equality check below.
    struct Identity;

    impl SampleEnhancer for Identity {
        fn name(&self) -> String { String::from("identity") }
        fn enhance(&self, sample: SamplePcm<'_>) -> EnhancedPcm { EnhancedPcm::unchanged(sample) }
    }

    #[test]
    fn an_image_round_trips_every_field_of_a_module() {
        let module = exhaustive_module();
        let image = leak_aligned(&module.to_image());
        let borrowed = Module::from_image(image).expect("the image reads back");

        assert_eq!(borrowed, module, "an image must round-trip a module field for field");
        assert!(borrowed.pcm_storage().is_borrowed(), "from_image must borrow the PCM, not copy it");
        assert!(borrowed.blob_storage().is_borrowed(), "from_image must borrow the pattern blob, not copy it");
    }

    #[test]
    fn a_copied_image_is_equal_to_a_borrowed_one() {
        let module = exhaustive_module();
        let bytes = module.to_image();
        let borrowed = Module::from_image(leak_aligned(&bytes)).expect("the image reads back");
        let copied = Module::from_image_copied(&bytes).expect("the image reads back copied");

        assert_eq!(copied, module);
        assert_eq!(copied, borrowed);
        assert!(!copied.pcm_storage().is_borrowed());
        assert!(!copied.blob_storage().is_borrowed());
    }

    #[test]
    fn a_misaligned_image_is_an_error_rather_than_a_silent_copy() {
        let module = exhaustive_module();
        let bytes = module.to_image();
        let misaligned = leak_misaligned(&bytes);

        assert_eq!(Module::from_image(misaligned), Err(MISALIGNED), "from_image must refuse rather than spend the RAM");
    }

    #[test]
    fn from_image_or_copy_takes_a_misaligned_image_and_copies_only_the_pcm() {
        let module = exhaustive_module();
        let bytes = module.to_image();
        let recovered = Module::from_image_or_copy(leak_misaligned(&bytes)).expect("the fallback reads a misaligned image");

        assert_eq!(recovered, module);
        assert!(!recovered.pcm_storage().is_borrowed(), "the PCM is the part that had to be copied");
        assert!(recovered.blob_storage().is_borrowed(), "bytes have no alignment to lose, so the blob still borrows");
    }

    #[test]
    fn from_image_or_copy_still_borrows_an_aligned_image() {
        let module = exhaustive_module();
        let image = leak_aligned(&module.to_image());
        let borrowed = Module::from_image_or_copy(image).expect("the image reads back");

        assert!(borrowed.pcm_storage().is_borrowed(), "the fallback must not copy what it could borrow");
    }

    #[test]
    fn a_borrowed_module_rebuilds_into_an_equal_owned_module() {
        let module = exhaustive_module();
        let borrowed = Module::from_image(leak_aligned(&module.to_image())).expect("the image reads back");
        let rebuilt = borrowed.enhanced(&Identity).expect("an identity rebuild");

        assert_eq!(rebuilt, module, "K5a's identity-rebuild equality must hold across borrowed storage");
        assert!(!rebuilt.pcm_storage().is_borrowed(), "a rebuild goes through the builder, which always owns");
    }

    #[test]
    fn a_clone_of_a_borrowed_module_stays_borrowed() {
        let module = exhaustive_module();
        let borrowed = Module::from_image(leak_aligned(&module.to_image())).expect("the image reads back");
        let cloned = borrowed.clone();

        assert!(cloned.pcm_storage().is_borrowed());
        assert_eq!(cloned, borrowed);
    }

    #[test]
    fn a_truncated_image_is_an_error_at_every_length() {
        let module = exhaustive_module();
        let bytes = module.to_image();
        for length in 0..bytes.len() {
            let truncated = bytes.get(..length).unwrap_or(&[]);
            assert!(Module::from_image_copied(truncated).is_err(), "a {length}-byte prefix of an image must not load");
        }
    }

    #[test]
    fn the_magic_the_version_and_the_reserved_flags_are_all_checked() {
        let module = exhaustive_module();
        let good = module.to_image();

        let mut bad_magic = good.clone();
        if let Some(byte) = bad_magic.get_mut(0) {
            *byte = b'X';
        }
        assert_eq!(Module::from_image_copied(&bad_magic), Err(Error::BadMagic));

        let mut bad_version = good.clone();
        if let Some(slot) = bad_version.get_mut(4..6) {
            slot.copy_from_slice(&(IMAGE_VERSION + 1).to_le_bytes());
        }
        assert!(matches!(Module::from_image_copied(&bad_version), Err(Error::Unsupported(_))));

        let mut bad_flags = good.clone();
        if let Some(slot) = bad_flags.get_mut(6..8) {
            slot.copy_from_slice(&1u16.to_le_bytes());
        }
        assert_eq!(Module::from_image_copied(&bad_flags), Err(RESERVED_FLAGS));
    }

    #[test]
    fn a_single_flipped_byte_never_panics() {
        let module = exhaustive_module();
        let good = module.to_image();
        for index in 0..good.len().min(2048) {
            let mut corrupt = good.clone();
            if let Some(byte) = corrupt.get_mut(index) {
                *byte = byte.wrapping_add(0x5A);
            }
            // Either answer is fine; that control comes back is the assertion.
            let _ = Module::from_image_copied(&corrupt);
        }
    }

    #[test]
    fn the_pcm_starts_at_a_four_byte_offset_within_the_image() {
        let module = exhaustive_module();
        let bytes = module.to_image();
        let parts = parse_image(&bytes).expect("the image parses");

        assert!(parts.pcm_bytes.start.is_multiple_of(IMAGE_ALIGNMENT), "the PCM's offset within the image must be 4-byte aligned");
        assert_eq!(parts.pcm_bytes.len(), module.image_pcm_bytes());
    }

    #[test]
    fn an_image_padded_out_to_a_partition_still_reads_and_still_borrows() {
        let module = exhaustive_module();
        let mut padded = module.to_image();
        padded.resize(4096, 0xFF);
        let borrowed = Module::from_image(leak_aligned(&padded)).expect("a padded image reads back");

        assert_eq!(borrowed, module, "bytes past the PCM belong to the partition, not to the image");
        assert!(borrowed.pcm_storage().is_borrowed());
    }

    #[test]
    fn an_empty_module_round_trips() {
        let mut builder = ModuleBuilder::new();
        builder.set_header(ModuleHeader::new(ModuleFormat::Mod, 1));
        let module = builder.build().expect("a header-only module is valid");
        let image = leak_aligned(&module.to_image());

        assert_eq!(Module::from_image(image), Ok(module));
    }

    #[test]
    fn every_enum_code_round_trips() {
        for code in 0..=u8::MAX {
            if let Ok(format) = module_format_from_code(code) {
                assert_eq!(module_format_code(format), code);
            }
            if let Ok(mode) = loop_mode_from_code(code) {
                assert_eq!(loop_mode_code(mode), code);
            }
            if let Ok(waveform) = auto_vibrato_waveform_from_code(code) {
                assert_eq!(auto_vibrato_waveform_code(waveform), code);
            }
            if let Ok(action) = new_note_action_from_code(code) {
                assert_eq!(new_note_action_code(action), code);
            }
            if let Ok(check) = duplicate_check_from_code(code) {
                assert_eq!(duplicate_check_code(check), code);
            }
            if let Ok(action) = duplicate_action_from_code(code) {
                assert_eq!(duplicate_action_code(action), code);
            }
        }
        for code in 0..=u16::MAX {
            if let Ok(dialect) = dialect_from_code(code) {
                assert_eq!(dialect_code(dialect), code);
            }
        }
        assert_eq!(dialect_from_code(u16::MAX), Err(BAD_ENUM));
        assert_eq!(module_format_from_code(u8::MAX), Err(BAD_ENUM));
    }
}
