[package]
name = "starplayer-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
starplayer = { workspace = true, features = ["std"] }
starplayer-archive = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
zip = { workspace = true }
